package com.example.sehrimibul

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView

class MainActivity : AppCompatActivity() {
    private lateinit var buttonsehir: Button
    private lateinit var plakatext: EditText
    private lateinit var bilgiler: TextView
    @SuppressLint("SetTextI18n")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        buttonsehir = findViewById(R.id.button)
        plakatext = findViewById(R.id.editTextNumber)
        bilgiler = findViewById(R.id.textview)

        buttonsehir.setOnClickListener {
            if (plakatext.text.isNotEmpty()) {
                when (plakatext.text.toString().toInt()) {
                    1 -> bilgiler.text = "Adana \n\n04.02.2021 TÜİK verilerine göre 5'i merkez ilçe (Seyhan, Yüreğir, Çukurova, Sarıçam, Karaisalı) olmak üzere toplam 15 ilçesi ve belediyesi vardır. Bu ilçelerde 831 mahalle bulunmaktadır. Adana; kuzeyinde Kayseri, doğusunda Osmaniye, kuzeydoğusunda Kahramanmaraş, güneydoğusunda Hatay, kuzeybatısında Niğde ve batısında Mersin illeri ve güneyinde Akdeniz ile çevrilidir.[3]\n" +
                            "\n" +
                            "Türkiye'deki altıncı büyük metropolitan alan olup ülkenin önde gelen tarım, ticaret ve kültür merkezlerinden biridir. Türkiye'deki maden zengini 4. bölge olan Adana; krom, demir, manganez, kurşun ve çinko yatakları açısından önem taşımaktadır.\n" +
                            "\n" +
                            "Adana'nın merkezi; Mersin, Adana, Osmaniye ve Hatay illerini kapsayan coğrafi, ekonomik ve kültürel bir bölge olan Çukurova'nın merkezinde bulunur. Yaklaşık 6,33 milyon insana ev sahipliği yapan bölgenin büyük bir bölümü, tarıma oldukça elverişli, geniş ve düz bir arazidir."
                    2 -> bilgiler.text = "Adıyaman \n" +
                            "\nTürkiye'nin Güneydoğu Anadolu Bölgesi'nin Orta Fırat Bölümü'nde bulunan bir ilidir. İdari merkezi Adıyaman şehridir. TÜİK 2021 sonu verilerine göre ilin nüfusu 632.459'dur.\n" +
                            "\n" +
                            "Doğusunda Diyarbakır, kuzeyinde Malatya, batısında Kahramanmaraş, güneyinde Gaziantep ve Şanlıurfa illeri ile çevrilidir. İlin doğusunda Torosların güneydoğu uzantısı olan Malatya dağları, güneydoğusunda Atatürk Baraj Gölü yer alır. Doğusundan Fırat Nehri ile çevrilidir. İlin kuzey kesimi genel anlamda dağlık ve engebeli iken güney kesiminde geniş ovalar bulunur.\n" +
                            "\n" +
                            "İl sınırları içerisindeki tek üniversite Adıyaman Üniversitesi'dir."
                    3 -> bilgiler.text = "Afyonkarahisar\n" +
                            "\n Ege Bölgesi'nin İç Batı Anadolu Bölümü'nde yer alan bir ildir. İl nüfusu 747.555'tir (31 Aralık 2022). Bu nüfusun %78,07'ü şehirlerde yaşamaktadır (31 Aralık 2021). İlin yüzölçümü 14.016 km²'dir. İlde km²'ye 53 kişi düşmektedir. (Bu sayı merkez ilçede 253’dür.) Afyonkarahisar sınırlarında merkez ilçeyle beraber 18 İlçe, 60 belediye, bu belediyelerde 448 mahalle ve ayrıca 420 köy vardır. "
                    4 -> bilgiler.text = "Ağrı\n" +
                            "\n Türkiye'nin Doğu Anadolu Bölgesi'nde Yukarı Murat-Van Bölümü'nde bulunan bir ildir. Adını kısmen sınırları içerisinde bulunan Ağrı Dağı'ndan almıştır. 1834 yılında bucak, 1869 yılında ilçe olan Ağrı, 1927 yılında il olmuştur. İlin doğusunda İran, kuzeyinde Kars, kuzeybatısında Erzurum, güneybatısında Muş ve Bitlis, güneyinde Van ve kuzeydoğusunda Iğdır bulunmaktadır.\n" +
                            "\n" +
                            "İlin nüfusu 524.644'tür. Bu nüfusun %60,58'i şehirlerde yaşamaktadır (2021 sonu).[2] Yüzölçümü 11.099 km2'dir, km2'ye 47 kişi düşmektedir. İl merkezi Ağrı'nın denizden yüksekliği: 1630 m.'dir. Rakımı en yüksek ilçesi Diyadin'dir (1933 m).\n" +
                            "\n" +
                            "2021 yılında TÜİK verilerine göre merkez ilçeyle beraber 8 ilçe, 12 belediye, bu belediyelerde 100 mahalle ve ayrıca 563 köy vardır.[2] "
                    5 -> bilgiler.text = "Amasya \n" +
                            "\nAmasya ilinin merkez şehridir. 2020 itibarıyla Amasya (merkez ilçe) 147.266 nüfusa sahiptir.[1]\n" +
                            "\n" +
                            "Orta Karadeniz Bölümü'nde yer alır. Anadolu'nun eski yerleşim alanlarından biridir. Hititlerden başlayarak çeşitli uygarlıkların merkezi olmuştur. Kentin bilinen en eski adı, söylendiği biçimi ile günümüze kadar hiçbir değişikliğe uğramadan gelen Amasya'dır. Eski kayıtlarda ve buluntularda Amesseia - Amacia - Amaccia ismi okunmaktadır. Amasya isminin açık bir şekilde okunduğu, Pers, Pontos ve Roma İmparatorluğu dönemlerinde ticarette kullanılan gümüş ve bronz sikkeler (paralar) üzerinde görmek mümkündür.\n" +
                            "\n" +
                            "Bazı sikkeler üzerinde Amaccia veya Amacia isimlerine rastlanılmaktadır. Amasya'nın fethinden önce ve sonrasında da Türkler, Amasseia'yı veya Amaccia, Amacia Türkçede söylendiği gibi Amasya yapmışlardır.[kaynak belirtilmeli]\n" +
                            "\n" +
                            "Tahminen MÖ 60 ve MS 19. yıllarda Amasya'da doğduğu bilinen ve Coğrafya ilminin mucidi olarak tanınan Strabon, yazdığı ünlü coğrafya kitabında Amasya'dan Amasseia olarak söz etmektedir. "
                    6 -> bilgiler.text = "Ankara \n\nAnkara , Türkiye'nin başkenti ve İstanbul'dan sonra en kalabalık ikinci ilidir.[7] Nüfusu 2023 yılı itibarıyla 5.782.285 kişidir. Bu nüfus; 25 ilçe ve bu ilçelere bağlı 1425 mahallede yaşamaktadır. İl genelinde nüfus yoğunluğu 215'tir. Nüfuslarına göre şehirler listesinde belediye sınırları göz önüne alınarak yapılan sıralamaya göre dünyada ise elli yedinci sırada yer almaktadır. Coğrafi olarak Türkiye'nin merkezine yakın bir konumda bulunur ve Batı Karadeniz Bölgesi'nde kalan kuzey kesimleri hariç, büyük bölümü İç Anadolu Bölgesi'nde yer alır. Yüzölçümü olarak Konya ve Sivas'tan sonra Türkiye'nin en büyük üçüncü ilidir. Bolu, Çankırı, Kırıkkale, Kırşehir, Aksaray, Konya ve Eskişehir illeri ile çevrilidir.\n" +
                            "\n" +
                            "Ankara'nın 13 Ekim 1923'te[8] başkent ilan edilmesinin ardından şehir hızla gelişmiş ve Türkiye'nin ikinci en kalabalık ili olmuştur. Türkiye Cumhuriyeti'nin ilk yıllarında ekonomisi tarım ve hayvancılığa dayanan ilin topraklarının yarısı hâlâ tarım amaçlı kullanılmaktadır. Ekonomik etkinlik büyük oranda ticaret ve sanayiye dayalıdır. Tarım ve hayvancılığın ağırlığı ise giderek azalmaktadır. Ankara ve civarındaki gerek kamu sektörü gerek özel sektör yatırımları, başka illerden büyük bir nüfus göçünü teşvik etmiştir. Cumhuriyetin kuruluşundan günümüze, nüfusu ülke nüfusunun iki katı hızda artmıştır. Nüfusun yaklaşık dörtte üçü hizmet sektörü olarak tanımlanabilecek memuriyet, ulaşım, haberleşme ve ticaret benzeri işlerde, dörtte biri sanayide, %2'si ise tarım alanında çalışır. Sanayi, özellikle tekstil, gıda ve inşaat sektörlerinde yoğunlaşmıştır. Günümüzde ise en çok savunma, metal ve motor sektörlerinde yatırım yapılmaktadır. Türkiye'nin en çok sayıda üniversiteye sahip ili olan Ankara'da ayrıca, üniversite diplomalı kişi oranı ülke ortalamasının iki katıdır. Bu eğitimli nüfus, teknoloji ağırlıklı yatırımların gereksinim duyduğu iş gücünü oluşturur. Ankara'dan otoyollar, demir yolu ve hava yoluyla Türkiye'nin diğer şehirlerine ulaşılır.\n" +
                            "\n" +
                            "Bilinen tarihi en az 10 bin yıl öncesine, Eski Taş Çağı'na ulaşan[9] Ankara, tarih öncesinden günümüze dek pek çok medeniyeti barındırmıştır. Hititler, Frigyalılar, Lidyalılar, Persler, Galatlar, Romalılar, Bizanslılar, Selçuklu Hanedanı, Osmanlılar ve nihayet Türkiye Cumhuriyeti, il topraklarını kontrolleri altında tutmuştur. Tektosagların ve Türkiye Cumhuriyeti'nin başkenti olan Ankara şehri ve Frigyalıların başkenti Gordion, il sınırları içinde yer alır. Yıldırım Bayezid'in Timurlenk'e yenik düştüğü Ankara Muharebesi Çubuk yakınlarında ve Türk Kurtuluş Savaşı'nın dönüm noktası olan Sakarya Muharebesi Polatlı yakınlarında yapılmıştır.\n" +
                            "\n" +
                            "Ankara kara iklimine sahiptir. Şehir dışındaki il topraklarının büyük kısmı tahıl tarlalarıyla kaplı platolardan oluşur. İlin çeşitli yerlerindeki doğal güzellikler korumaya alınmış, dinlenme ve eğlence amaçlı kullanıma sunulmuştur. İlin adını taşıyan tavşanı, keçisi, atı ve kedisi dünya çapında bilinir, armudu, çiğdemi, yerel yemeklerden Ankara tavası ve Kızılcahamam ve Beypazarı'nın maden suyu ise ülke çapında tanınır. "
                    7 -> bilgiler.text = "Antalya \n\n Antalya, Türkiye'nin bir ili ve en kalabalık beşinci şehridir. 2022 sonu itibarıyla il nüfusu 2.688.004'dür.[3] Türkiye'de \"turizmin başkenti\" olarak görülmektedir.[4] Özellikle yaz aylarında turist sayısı artar. Şehrin yüzölçümü 20.177 km2dir.[5] İlde km2ye 130 kişi düşmektedir. En kalabalık ilçesi 2021 yılı itibarıyla 591.895 kişiyle Kepez ilçesidir. Nüfus yoğunluğunun en fazla olduğu ilçe ise km2 başına 5429 kişi ile Muratpaşa ilçesidir. 19 ilçe ve belediye bulunan Antalya şehrinin bu belediyelerinde toplam 914 mahalle bulunmaktadır.\n" +
                            "\n" +
                            "Tamamı Akdeniz Bölgesi'nin batısında yer alır ve Antalya Körfezi'yle Batı Torosların arasında kurulmuştur. Yüzölçümü bakımından Türkiye'nin beşinci büyük ilidir.[6] Güneyinde Akdeniz, batısında Muğla, kuzeyinde Burdur ve Isparta, kuzeydoğusunda Konya, doğusunda ise Karaman ve Mersin illeri vardır.\n" +
                            "\n" +
                            "Antalya şehri, 1980 yılından sonra uygun iklim koşulları ve turizm etkinlikleri nedeniyle hızla gelişmiş ve buna paralel olarak il de günümüzde Türkiye'nin en kalabalık beşinci ili olmuştur.[7] Antalya'da ekonomik hayat büyük oranda ticaret, tarım ve turizme dayalıdır.\n" +
                            "\n" +
                            "Antalya ilinin kapsadığı bölge tarih öncesinden günümüze dek pek çok medeniyeti barındırmıştır ve Türkiye'de en çok antik kent bulunan ildir.[8] Sırasıyla Likyalılar, Lidyalılar, Pamfilyalılar, Bergamalılar, Romalılar, Bizanslılar, Selçuklu Hanedanı, Osmanlılar ve son olarak da Türkiye Cumhuriyeti hakimiyetinde bulunan Antalya bu medeniyetlerin hiçbirine başkentlik yapmamıştır.[9]\n" +
                            "\n" +
                            "İlin tamamı Akdeniz Bölgesi'nin Antalya Bölümü'nde yer alır ve Akdeniz ikliminin etki sahasındadır. Yerleşim yerleri haricindeki il topraklarının büyük kısmı tahıl tarlalarıyla kaplı platolardan oluşur.[10]\n" +
                            "\n" +
                            "Türk Silahlı Kuvvetleri Kara Kuvvetleri Komutanlığına bağlı 3. Piyade Eğitim Tugayı Komutanlığı ve Hava Kuvvetleri Komutanlığına bağlı Hava Meydan Komutanlığı Antalya'da bulunmaktadır.[11][12]\n" +
                            "\n" +
                            "Antalya 2015 yılı G20 Zirvesi'nin ve Expo 2016'nın ev sahibidir. "
                    8 -> bilgiler.text = "Artvin \n\nArtvin, Türkiye'nin Karadeniz Bölgesi'nin Doğu Karadeniz Bölümü'nde yer alan, Karadeniz'e kıyısı bulunan bir ildir. İl, Türkiye'nin Gürcistan'la olan sınırında yer alan kuzeydoğu köşesidir. Doğusunda Ardahan ili, güneyinde Erzurum ili ve batısında Rize ili vardır.\n" +
                            "\n" +
                            "2019 Yılı verilerine göre nüfusu 170.875’dir.[4] Bu nüfusun %62,4'ü şehirlerde yaşamaktadır. İlin yüzölçümü 7.436 km²'dir. İlde km²'ye 23 kişi düşmektedir. (Bu sayı merkez ilçede 30'dur.) İl merkezinin denizden yüksekliği: 530 m.'dir.\n" +
                            "\n" +
                            "2020 yılında TÜİK verilerine göre merkez ilçeyle beraber 9 ilçe, 9 belediye, bu belediyelerde 39 mahalle ve ayrıca 320 köyü vardır.[2]\n" +
                            "\n" +
                            "Coğrafi ve kültürel yapısıyla Anadolu'nun diğer bölgelerinden keskin çizgilerle ayrılır. Yüzey şekilleri çok engebelidir. İklim çeşitliliği fazladır. İlin en önemli akarsuyu, 1956 yılına kadar adını veren Çoruh Nehri'dir. Artvin boğalarıyla meşhur bir il olup simgesi boğadır. Artvin il topraklarının yaklaşık %55’ini ormanlık alanlar kaplamıştır. Murgul'da bakır madeni vardır. Tarihte genellikle Livane ve Çoruh adıyla bilinir. Artvin il nüfusunu Gürcüler, Hemşinliler, Ahıska Türkleri ve Lazlar oluşturur.\n" +
                            "\n" +
                            "Millî parklarıyla ünlüdür. Şavşat ilçesinde bulunan Karagöl Sahara Millî Parkı içerisinde bulunan Şavşat-Karagöl ve Borçka-Karagöl turistik yerlerden bazılarıdır. Efeler-Gorgit Tabiatı Koruma Alanı esas olmak üzere Camili yöresi Birleşmiş Milletler Eğitim, Bilim ve Kültür Örgütü tarafından biyosfer rezerv alanı olarak belirlenen Türkiye'deki tek bölgedir ve bir dünya mirası olarak görülmektedir.[5]\n" +
                            "\n" +
                            "İlin bir önceki adı Çoruh olup, TBMM'nde kabul edilen 17 Şubat 1956 tarih ve 6668 sayılı kanunla Artvin olmuştur.[6] "
                    9 -> bilgiler.text = "Aydın \n\n Aydın, Türkiye'nin bir ili ve en kalabalık yirminci şehridir. Ege Bölgesi'nde yer alan, turizm ve tarım açısından en gelişmiş illerdendir. Kuzeyinde İzmir, kuzeydoğusunda Manisa, doğusunda Denizli, güneyinde Muğla illeri, batısında Ege Denizi bulunmaktadır. 2022 itibarıyla 1.134.031[5] kişilik nüfusuyla Ege Bölgesi'nin üçüncü büyük ilidir. 17 ilçesi vardır."
                    10 -> bilgiler.text = "Balıkesir \n\n Balıkesir, Türkiye'nin bir ili ve en kalabalık on yedinci şehri. Marmara Bölgesi'nin Güney Marmara Bölümü'nde, topraklarının bir kısmı ise Ege Bölgesi'nde yer alan ilin hem Marmara hem de Ege Denizi'ne kıyısı bulunur. Türkiye genelinde ise iki deniz ile komşu olan sadece 6 il vardır.[4] İl, Kuzeybatı Anadolu'da bulunmaktadır. Doğusunda Bursa ve Kütahya illeri, güneyinde Manisa ve İzmir illeri ve batısında Çanakkale ili vardır.[5] Ayvalık ilçesinden de Yunanistan'ın Midilli Adası'na komşudur.[6]\n" +
                            "\n" +
                            "2019 Yılı verilerine göre nüfusu 1.228.620’dir.[7] İlin yüzölçümü 14.583 m²'dir. İlde km²'ye 82 kişi düşmektedir. Yoğunluğun en fazla olduğu ilçe, 254 kişi ile Karesi'dir. İlin denizden yüksekliği 145 metredir. 2016 yılında TÜİK verilerine göre 20 ilçe ve belediye, bu belediyelerde toplam 1129 mahalle bulunmaktadır.\n" +
                            "\n" +
                            "Tarihte genellikle Misya ve Karesi adlarıyla bilinen Balıkesir yöresi, zamanla Roma, Bizans, Anadolu Selçuklu, Karesi Beyliği ve Osmanlı egemenliğinde kalmıştır. Temel geçim kaynağı tarım ve hayvancılık olup bamya, börülce, kavun, zeytin, zeytinyağı, kelle peyniri gibi zirai ürünleri ile ayrıca daha çok yerli turizmde öne çıkan sahil kasabalarıyla meşhurdur. Yağcıbedir halısı, kolonyası, kaymaklısı, kozak üzümü, ayvalık tostu, susurluk ayranı, saçaklı mantısı ve höşmerimi diğer bilinen yöresel ürünleridir.\n" +
                            "\n" +
                            "Türk Silahlı Kuvvetleri Hava Kuvvetleri Komutanlığı'nın ilk jet üssü olan 9. Ana Jet Üs Komutanlığı ile 6. Ana Jet Üs Komutanlığı Balıkesir'de bulunmaktadır. "
                    11 -> bilgiler.text = "Bilecik \n\nBilecik ili, Marmara Bölgesi'nin güney doğusunda; Marmara, Karadeniz, İç Anadolu Bölgesi ve Ege Bölgelerinin kesim noktaları üzerinde yer alır. İlin bilinen en eski isimleri arasında Agrilion ve Belekoma vardır. Bilecik, Osmanlı İmparatorluğu'nun doğduğu topraklardadır. Her yıl Ertuğrul Gazi'yi Anma ve Söğüt şenlikleri, Bilecik iline bağlı Söğüt'te yapılmaktadır. Bölgede zengin mermer ocakları mevcuttur. Sakarya ırmağının etrafında kurulan ve göletleri ve derelerinin zenginliği ile tanınan yöre antik çağlardan günümüze tarihin izlerini taşır. Şehirdeki Şeyh Edebali Türbesi, tüm Türkiye'den ziyaretçi almaktadır. Türk Kurtuluş Savaşı'na ait izler, Bilecik ilinin ilk yerleşim yeri olan Şeyh Edebali Türbesi'nin çevresinde hâlen görülebilir. Bunlara örnek olarak bir kısmı savaş sırasında yıkılmış olan minare gösterilebilir. q"
                    12 -> bilgiler.text = "Bingöl \n\nBingöl, (Zazaca: Çolik/Çolig) Türkiye'nin Doğu Anadolu Bölgesi’nin Yukarı Fırat Bölümü’nde yer alan bir ildir.\n" +
                            "\n" +
                            "İl nüfusu: 281.768'dir. Bu nüfusun %67,7'si şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 8.004  km2'dir. İlde  km2'ye 35 kişi düşmektedir. (Bu sayı merkez ilçede 91’dir.)[2] İl merkezinin denizden yüksekliği: 1159 m'dir.\n" +
                            "\n" +
                            "04 Şubat 2020 TÜİK verilerine göre 8 İlçe, 11 belediye, bu belediyelerde 68 mahalle, ayrıca 320 köy bulunmaktadır.[2]Bingöl, (Zazaca: Çolik/Çolig) Türkiye'nin Doğu Anadolu Bölgesi’nin Yukarı Fırat Bölümü’nde yer alan bir ildir.\n" +
                            "\n" +
                            "İl nüfusu: 281.768'dir. Bu nüfusun %67,7'si şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 8.004  km2'dir. İlde  km2'ye 35 kişi düşmektedir. (Bu sayı merkez ilçede 91’dir.)[2] İl merkezinin denizden yüksekliği: 1159 m'dir.\n" +
                            "\n" +
                            "04 Şubat 2020 TÜİK verilerine göre 8 İlçe, 11 belediye, bu belediyelerde 68 mahalle, ayrıca 320 köy bulunmaktadır.[2]"
                    13 -> bilgiler.text = "Bitlis\n\nBitlis İli, Türkiye'nin Doğu Anadolu Bölgesi Yukarı Murat-Van Bölümü'nde yer alan bir ildir.\n" +
                            "\n" +
                            "İl nüfusu: 350.994'dür. Bu nüfusun %65,1'i şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 8.294  km2'dir. İlde  km2'ye 42 kişi düşmektedir. (Bu sayı Güroymak'ta 94’dür.) İlde yıllık nüfus artış oranı  % 0,83 olmuştur.[3] İl merkezinin denizden yüksekliği: 1637 m'dir.\n" +
                            "\n" +
                            "04 Şubat 2021 TÜİK verilerine göre 7 İlçe, 13 belediye, bu belediyelerde 123 mahalle, ayrıca 348 köy bulunmaktadır.[3]\n" +
                            "\n" +
                            "İsmi Makedonya Kralı Büyük İskender’in şehirdeki kaleyi yaptırttığı komutanlarından Bedlis’ten gelmektedir. Tarihsel yapıların ağırlıkta olduğu bir vadi içinde kurulduğundan “Vadideki Güzel Şehir” diye anılır. "
                    14 -> bilgiler.text = "Bolu\n\nBolu, Türkiye'nin Karadeniz Bölgesi'nin Batı Karadeniz Bölümü'nde yer alan bir il.\n" +
                            "\n" +
                            "Bolu ili nüfusu: 314.802'dir. Bu nüfusun %74,4'ü şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 8.313  km2'dir. İlde  km2'ye 38 kişi düşmektedir. (Bu sayı Merkezde 132’dir.) İlde yıllık nüfus % 0,42 oranında azalmıştır.[2] İl merkezinin denizden yüksekliği: 741 m.'dir.\n" +
                            "\n" +
                            "2020 yılında TÜİK verilerine göre merkez ilçeyle beraber 9 İlçe, 12 belediye, bu belediyelerde 93 mahalle ve ayrıca 487 köyü vardır.[2] "
                    15 -> bilgiler.text = "Burdur \n\nBurdur, Türkiye'nin Akdeniz Bölgesi'nde bulunan bir ildir. Burdur'un plaka kodu 15'tir.\n" +
                            "\n" +
                            "Burdur ili nüfusu: 273.716'dır.[5] Bu nüfusun %72,4'ü şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 7.175 km2'dir. İlde km2'ye 38 kişi düşmektedir. (Bu sayı merkez ilçede 71’dir.)\n" +
                            "\n" +
                            "İlde yıllık nüfus %1,37 oranında azalmıştır.[6] İl merkezinin denizden yüksekliği 963 metredir.\n" +
                            "\n" +
                            "2021 yılında TÜİK verilerine göre merkez ilçeyle beraber 11 ilçe ve 15 belediye vardır.\n" +
                            "\n" +
                            "Bu belediyelerde 127 mahalle,ayrıca 193 köy vardır.[6] "
                    16 -> bilgiler.text = "Bursa\n\nBursa (Yunanca: Προῦσα Prussa, Latince: Prusa), Türkiye'nin bir ili ve en kalabalık dördüncü şehri. 2022 itibarıyla 3.194.720[2] nüfusa sahiptir. Marmara Bölgesinin Güney Marmara bölümünde, 40° kuzey enlem ve 29° doğu boylam daireleri arasında yer alır. Eski adı Hüdavendigâr'dır. Kuzeyinde Marmara Denizi ve Yalova, kuzeydoğuda Kocaeli ve Sakarya, doğuda Bilecik, güneyde Kütahya ve batıda Balıkesir illeri ile çevrilidir.\n" +
                            "\n" +
                            "Ekonomik açıdan Türkiye'nin en gelişmiş kentlerinden biri olan Bursa doğal ve tarihsel zenginlikleriyle de önem taşır. Bursa'da en çok Osmanlı İmparatorluğu'nun kuruluş dönemine ait tarihi eserlerin bulunmasının sebebi ise, Bursa'nın Osmanlı Devletinin ilk başkenti olmasıdır. Bursa alışveriş merkezleri, parkları, müzeleri ve çarşısıyla bölgede öne çıkar. Ayrıca Bursa Marmara bölgesinin İstanbul'dan sonra gelen ikinci büyük şehridir. Türkiye'nin en önemli birkaç sanayi kentinden biridir. Şehir İstanbul'dan sonra en büyük ikinci ihracatı gerçekleştirmektedir. Şehrin futbol takımı Bursaspor 2009-10 sezonunda Süper Lig şampiyonudur.\n" +
                            "\n" +
                            "Bursa, sanayi istatistiklerine göre Türkiye'nin en büyük sanayi kenti ve otomotiv üretim merkezidir. CNN International tarafından Türkiye'nin Detroit'i yakıştırması yapılmıştır. Tofaş-Fiat, Renault, Peugeot, Karsan, TOGG, Bosch, Cobra Güleryüz ve Akia otobüs fabrikaları Bursa'da bulunmaktadır. Aynı zamanda binek ve ticari araçların yan sanayi ve yedek parça fabrikalarının büyük kısmı Bursa'dadır. Bursa'nın otomotiv sanayisi bakımından Türkiye tarihinde bıraktığı izler dolayısıyla TOFAŞ tarafından şehir merkezine yapılan TOFAŞ Anadolu Arabaları Müzesi de kentin simgelerinden biri haline gelmiştir.  "
                    17 -> bilgiler.text = "Çanakkale\n\nÇanakkale, Türkiye'nin kuzeybatısında, Marmara Bölgesi içinde yer alan il. 31 Aralık 2019 itibarıyla Çanakkale ili içerisindeki 12 ilçe ve bu ilçelere bağlı 81 mahallede yaşayan toplam nüfus 542.157 kişidir.[4] Türkiye'de İstanbul ile birlikte, Asya ve Avrupa kıtalarında bulunan ve dolayısıyla boğazı olan iki ilden biridir. Yüzölçümü 9.817 km²'dir[5]. Komşu illeri Edirne, Tekirdağ ve Balıkesir'dir.\n" +
                            "\n" +
                            "1 Şubat 2019 TÜİK verilerine göre 12 İlçe, 23 belediye, bu belediyelerde 81 mahalle, ayrıca 576 köy bulunmaktadır.[3]\n" +
                            "\n" +
                            "Türkiye'nin nüfus sıralamasında 40. il olan Çanakkale'de günümüzde bir üniversite vardır. Çanakkale'den diğer şehirlere ulaşım otoyollar ve hava yoluyla sağlanır.\n" +
                            "\n" +
                            "Çanakkale'deki iklim, ilin coğrafyası nedeniyle geçiş niteliği taşısa da yoğunlukla Akdeniz iklimi özelliklerine sahiptir.[6] Anadolu'nun en batı noktası olan Baba Burnu ile Türkiye'nin en batı noktası Gökçeada'daki İncirburnu il sınırları içindedir. Ege Denizi'nde Türkiye'ye ait en büyük adalar olan Bozcaada ve Gökçeada ilçeleri de Çanakkale'ye bağlıdır.  "
                    18 -> bilgiler.text = "Çankırı\n\nÇankırı, Türkiye'nin İç Anadolu Bölgesinde bulunan bir ildir. Kuzey ilçeleri Karadeniz Bölgesi'nde kalan il, kuzeyde Karabük ve Kastamonu, doğuda Çorum, güneydoğuda Kırıkkale, güneyde Ankara ve batıda Bolu illeriyle çevrilidir.\n" +
                            "\n" +
                            "Çankırı ili nüfusu: 192.428'dir. Bu nüfusun %73,8'i şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 7.542  km2'dir. İlde  km2'ye 26 kişi düşmektedir. (Bu sayı Merkezde 160’tır.) İlde yıllık nüfus % 1,72 oranında azalmıştır.[3] İl merkezinin denizden yüksekliği: 730 m.'dir.\n" +
                            "\n" +
                            "2020 yılında TÜİK verilerine göre merkez ilçeyle beraber 12 ilçe, 15 belediye, bu belediyelerde 96 mahalle ve ayrıca 371 köyü vardır.[3]  "
                    19 -> bilgiler.text = "Çorum\n\nÇorum, Türkiye'nin Karadeniz Bölgesi'nin Orta Karadeniz bölümünde yer alan bir ildir.\n" +
                            "\n" +
                            "04 Şubat 2021 TÜİK verilerine göre  merkez ilçeyle beraber 14 İlçe, 16 belediye, bu belediyelerde 126 mahalle, ayrıca 759 köy bulunmaktadır.[3]\n" +
                            "\n" +
                            "Çorum ili, leblebisi ile tanınır. İlde toprak ve makine endüstrisi oldukça gelişmiştir. Osmancık ilçesinde pirinç üretimi etkin bir şekilde yapılmaktadır. Kapari bitkisinin Türkiye'deki anavatanı Osmancık ilçesidir.  "
                    20 -> bilgiler.text = "Denizli\n\nDenizli, Türkiye'de Ege Bölgesi'nde yer alan bir ildir.[4] Nüfusu 2021 yılı itibarıyla 1.051.056'dir.[2] Ege Bölgesi'nde İzmir, Manisa ve Aydın'dan sonra dördüncü Büyükşehir'dir. Tekstil sanayi, metal, gıda ürünleri ve yöreye has Denizli horozu ile meşhurdur. Anadolu Yarımadası'nın güneybatı, Ege Bölgesi'nin güneydoğusunda yer alır. Ege ve Akdeniz Bölgeleri arasında bir geçit durumundadır. Denizli ilinin her iki bölge üzerinde de toprakları vardır. Denizli ili 28° 38' - 30° 05' doğu meridyenleri (doğu uç noktası; Çivril ilçesi Gümüşsu - Gökgöl Köyü, Dinar sınırında Efekli Tepe, batı uç Aydın, Manisa; güneyde Muğla; kuzeyde Uşak illeri ile komşudur.) Yüzölçümü 12.134 km²,[3] denizden yüksekliği ise 209 m'dir.\n" +
                            "\n" +
                            "Bir sanayi, ihracat ve ticaret merkezi olan Denizli, aynı zamanda altmış beş bine yaklaşan üniversite öğrencisine ev sahipliği yapmaktadır. Bir yılda milyonlarca yerli ve yabancı turisti ağırlayan il, bir turizm kenti olmasının yanı sıra düzenlenen yerel, ulusal ve uluslararası etkinliklerle eğitim, kongre, kültür ve sanat merkezi özelliğindedir. GEKA (Güney Ege Kalkınma Ajansı) merkezi Denizli'dedir.[5]\n" +
                            "\n" +
                            "Akdağ'ın (Babadağ) kuzey yamaçları eteklerinde, Büyük Menderes'in kolu olan Aksu çayına kavuşan derelerle hafifçe yarılmış bir plato üzerinde yer alan Denizli, yeni bir kenttir. Asıl kent buradan 6-7 kilometre kadar kuzeydeki Laodikeia (Laodicaea) adlı yerdeydi. Selçuklular ve Bizanslılar arasındaki savaşlar sonucu yıkıma uğrayan ve özellikle suyolları bozulan Laodikeia zamanla terk edilmeye başlanmış ve yerleşme 11. yüzyıldan başlayarak bol su kaynaklarının bulunduğu Denizli, Ladik'e doğru yer değiştirmeye başlamıştır. Kent, 1702-1703'teki bir deprem sırasında büyük zarara uğramış ve daha sonra yeniden kurulmuştur. Ege kıyılarından iç kesimlere sokulan doğal bir yol üzerinde bulunan Denizli, özellikle 1950'li yıllarda karayollarının düzelmesinden sonra, bu konumunun ve çevresindeki tarım etkinliklerinin gelişmesi sonucu hızla kalabalıklaşmış ve 1950'de 22.000 olan nüfusu, aradan geçen 60 yıl içinde yaklaşık 25 kat artmıştır. Sanayisi, turizmi, ticareti ve hizmet sektörü çok gelişmiş olan Denizli, Türkiye'nin en kalkınmış kentlerinden biridir. Anadolu Kaplanları'nın başıdır. Dünya'da tekstilin en önemli başkentleri arasındadır. Ayrıca Serinhisar ilçesi de Türkiye'nin leblebi ve leblebi ürünleri ihtiyacının %85 civarını karşılamaktadır. Denizli, Türkiye'nin en büyük 10 ekonomisi arasındadır. Kent, havlu, bornoz ve ev tekstilinde ABD ve AB pazarında iyi bir prestije sahiptir. Havası ve doğası Ege Bölgesi'nin ortalamalarını yansıtır. Şehrin birkaç noktasında horoz heykeli bulunur. Dünyaca bilinen doğa harikası Pamukkale de şehrin simgelerinden biridir. Pamukkale, UNESCO'nun dünya kültür mirası listesindedir. Karahayıt da uluslararası termal bir merkezdir. Ayrıca en yüksek dağı Honaz Dağı aynı zamanda Ege Bölgesi'nin en yüksek dağıdır (2532 m). Şehirde UNESCO'ya giren Hierapolis, Laodikeia, Tripolis, Tabea, Attoudda, Eumenea, Collossea vb. birçok antik kent bulunmaktadır.[6]  "
                    21 -> bilgiler.text = "Diyarbakır\n\nDiyarbakır (Kürtçe: Amed,[2][3] Zazaca: Diyarbekır[4]), Türkiye'nin Güneydoğu Anadolu Bölgesi'nde bulunan bir şehirdir.[5] İlin yüzölçümü 15.168 km2'dir. Valiliğin denizden yüksekliği 660 m'dir. Adıyaman, Batman, Bingöl, Elazığ, Mardin, Muş, Malatya ve Şanlıurfa illeri ile komşudur. 17 tane ilçeye sahiptir.\n" +
                            "\n" +
                            "Üzerinde tarihi Diyarbakır Kalesi'nin bulunduğu Dicle Nehri kıyısında yüksek bir plato çevresinde yer alan şehir, Türkiye'nin Güneydoğu Anadolu Bölgesi'nin yüzölçümü bakımından Şanlıurfa'dan sonraki ikinci büyük şehridir.[6] Karasal iklimin hâkim olduğu şehirde yazlar son derece sıcak ve kurak geçer iken, kışlar ise soğuk, sert ve yağışlı geçer.[7] Diyarbakır,[8] yaklaşık 9000 yıllık tarihi bir geçmişe sahiptir.\n" +
                            "\n" +
                            "Yontma Taş ve Mezolitik devirlerinde şehrin çevresindeki bazı mağaralarda yaşanmış olduğu, yapılan arkeolojik araştırmalar ile anlaşılmıştır. Eğil-Silvan yakınlarındaki Hassuni Mağaraları ve Dicle kolları üzerinde, Ergani yakınlarındaki Hilar Mağaraları'nda bu çağa ait birtakım kalıntılar tespit edilmiştir. Son yapılan arkeolojik kazılarda ise, Ergani ilçesi yakınlarında bulunan, Neolitik Dönem'e tarihlenen ve MÖ 8000-6000 yılına ait olduğu düşünülen Çayönü yerleşkesi ve benzeri tarihi örnekler, şehrin geçmişinin canlılığını bir kez daha ortaya koymuştur.[9] Tarih boyunca Amida, Amid, Kara-Amid, Diyar-Bekr, Diyarbekir gibi adları alan kent, Güneydoğu Anadolu'nun tam orta bölümünde, El-Cezire denilen, Mezopotamya'nın kuzey kısmında yer almaktadır.[9]\n" +
                            "\n" +
                            "Şehrin kent merkezinde, MÖ 3000 civarında Hitit ve Hurri-Mittani egemenliği yaşanmıştır. MÖ 1260 yılına kadar süren bu egemenlikten sonra sırasıyla Asurlular, Aramiler, Urartular, İskitler, İran'daki Medler, yine Antik İran'daki Ahamenişler (Persler), Büyük İskender'in komutasındaki Makedonyalılar, Selevkoslar, Partlar, Ermeniler, Roma İmparatorluğu, Sasani İmparatorluğu ve Bizans İmparatorluğu şehre hâkim olmuşlardır. İslam'ın doğuşundan ve Peygamber Muhammed'in ölümünden sonra, Ömer döneminde İslam ordusu Diyarbakır'ı ve çevresini fethetmiş ve Halid bin Velid, Diyarbakır'a giren ilk Müslüman kumandan olmuştur. Diyarbakır böylece bir eyalet olarak İslam Devleti'ne bağlandı. Dört Halife Dönemi'nden sonra Emeviler, Abbasiler, Hamdaniler ve Mervaniler bu kente sahip olmuşlardır. Selçuklu Türkleri, İnaloğulları ve Artukluların da egemenliğinden sonra, 12. yüzyılda kurulan Eyyûbîler Devleti ve 13. yüzyılda da Moğol istilaları sonucu Moğollar şehre sahip olmuşlardır. Akkoyunlular döneminde devlete başkentlik yapan şehir, daha sonra Şii Safevîler ve akabinde I. Selim döneminde Osmanlı İmparatorluğu'nun eline geçmiştir.[10]  "
                    22 -> bilgiler.text = "Edirne \n\nEdirne Türkiye'nin Edirne ilinde yer alan şehir ve aynı ilin merkez ilçesi. Marmara Bölgesi'nin Trakya kesiminde, Yunanistan ve Bulgaristan sınırında yer almaktadır. Edirne, 1363'den 1453'e kadar Osmanlı İmparatorluğu'nun başkentiydi. 2020 sayımına göre toplam nüfusu 180.901'dir. "
                    23 -> bilgiler.text = "Elazığ\n\nElazığ (Türkçe telaffuz: /ˈelazɯː/; eski adları ile: Harput, Ma‘mûretü'l-Azîz,[not 1] El-Azîz,[not 2] Kürtçe: Xarpêt), Türkiye'nin Doğu Anadolu Bölgesi'nde Yukarı Fırat Havzası'nda bulunan, on bir ilçeden oluşan il. Konumu itibarıyla; ili doğudan Bingöl, kuzeyden Keban Baraj Gölü aracılığıyla Tunceli, batı ve güneybatıdan Karakaya Baraj Gölü vasıtasıyla Malatya, kuzey batıdan Erzincan illerinin arazileri çevrelemektedir. İlin sınırları 8.327 km²si kara, 826 km²si baraj ve doğal göl olmak üzere toplam 9153 km²lik alanı kapsamaktadır.\n" +
                            "\n" +
                            "Forbes'e göre 2021 yılında Doğu ve Güney Doğu Anadolu Bölgesi'nin en yaşanılabilir ili, Türkiye'nin ise en yaşanabilir 19. ili seçilmiştir[3]. Halk arasında Elazığ'lı olanlara, Elazığ ağzında kardeş ve ağabey anlamlarına gelen Gakgoş hitabı kullanılır.[4] İlin tarihi MÖ 20. yüzyıla dayanır.[5] Tarihte Anadolu'yu Mezopotamya'ya bağlayan kervan yollarının geçiş güzergâhı içinde önemli yerleşim yeri olmuş, birçok kültüre ev sahipliği yapmıştır.[6] Müslüman, Rum, Ermeni ve Süryani halklarının uzun yıllar birlikte yaşadığı bu bölgede günümüzde hâlâ farklı kültür ve medeniyetlerin kalıntıları görülmektedir.[6] Elaziz'in adı, 17 Aralık 1937 tarih ve 3785 sayılı Resmi Gazete'de yayımlanan 10 Aralık 1937 tarih ve 7806 sayılı kararname ile Elazığ olarak değiştirilmiştir.[7][8]  "
                    24 -> bilgiler.text = "Erzincan\n\nErzincan, Doğu Anadolu Bölgesi’nin Yukarı Fırat Bölümü’nde Tarihi İpek Yolu'nun üzerinde yer alır. 2020 nüfus sayımına göre il nüfusu 234.431'dir. Bu nüfusun %81,5'i şehirlerde yaşamaktadır. İlin yüzölçümü 11.815 km2'dir. İlde km2'ye 20 kişi düşmektedir.[4]\n" +
                            "\n" +
                            "Merkez ilçeyle beraber 9 ilçe, 15 belediye, bu belediyelerde 159 mahalle, ayrıca 522 köy bulunmaktadır.[4]  "
                    25 -> bilgiler.text = "Erzurum \n\nErzurum Türkiye'nin 81 ilinden biridir.[3] Erzurum Ovası'nın güneydoğu kenarında, bu ova ile Palandöken dağının temas sahasında kurulmuş olan Erzurum şehri, 749,754 [2] nüfusu ile Doğu Anadolu Bölgesi'nin en büyük üçüncü ilidir. Denizden yüksekliği yaklaşık 1900 m olan Erzurum, tarihin ilk dönemlerinden beri yerleşim yeridir. Şehir, tarihî eserleri ve kış sporları tesisleriyle de tanınır. Yüzölçümü bakımından Türkiye'nin en büyük dördüncü ili olan Erzurum'da, temel geçim kaynağı tarım ve hayvancılık olup şehir son yıllarda kış turizmiyle de öne çıkmaktadır. Soğuk iklimi sebebiyle sanayisi gelişmemiştir. 25.005 km² yüzölçümüne sahip il arazisinin %15,17'si tarımsal amaçlı olarak kullanılabilir konumdadır.[4] "
                    26 -> bilgiler.text = "Eskişehir \n\nEskişehir, Türkiye'nin bir ili ve en kalabalık yirmi beşinci şehridir. Ayrıca nüfus bakımından Ankara, Konya, Kayseri'den sonra İç Anadolu bölgesinin en büyük 4. ilidir. 1993 yılında çıkarılan kanunla Büyükşehir Belediyesi olmuştur. Nüfusu 2021 yılı TÜİK istatistiklerine göre 898.369'dur.[2] Ortasından Porsuk Çayı geçen şehir, içerisinde Osmangazi Üniversitesi, Eskişehir Teknik Üniversitesi ve Anadolu Üniversitesinin bulunması nedeniyle bir öğrenci kenti görünümündedir.\n" +
                            "\n" +
                            "Met helvası, nuga helvası, haşhaşlı çörek, Kalabak suyu, çibörek ve lületaşı ile meşhurdur. Ayrıca balaban kebabı da Eskişehir mutfağında önemli bir yer almaktadır. İşlenebilir lületaşı, Türkiye'de yalnızca Eskişehir'de çıkarıldığı için Eskişehir taşı olarak bilinir.[3] Türkiye'de Eskişehir ve Sivrihisar dolaylarında yetişen bir çoban köpeği olan akbaş da şehre ait önemli değerlerdendir.[4] Sanat kurumları ve tesisleri ile kültür ve sanatta gelişmiş bir şehirdir. Anadolu Üniversitesi ve büyükşehir belediyesi bünyesinde iki adet senfoni orkestrası bulunmaktadır. Ayrıca her yıl düzenlenen Uluslararası Eskişehir Festivali ile şehirde müzik, tiyatro, resim ve sinema dallarında sergiler ve gösteriler yapılmaktadır.[5]\n" +
                            "\n" +
                            "Eskişehir günümüze kadar değişik uygarlıklar altında varlığını sürdürmüştür. Üzerinde kurulan medeniyetlerden bazıları Frigya, Bizans, Anadolu Selçukluları ve Osmanlı İmparatorluğu'dur.[6]\n" +
                            "\n" +
                            "Türk Silahlı Kuvvetleri Hava Kuvvetleri Komutanlığı'na bağlı Muharip Hava Kuvveti, Hava Füze Savunma Komutanlığı, 1. Hava İkmal ve Bakım Merkez Komutanlığı ve 1. Ana Jet Üs Komutanlığı da Eskişehir'de bulunmaktadır. Ayrıca hem askerî hem de sivil havaalanı Hasan Polatkan Havalimanı bulunmaktadır.\n" +
                            "\n" +
                            "Eskişehir 2013 yılında Türk Dünyası Kültür Başkenti ve UNESCO Somut Olmayan Kültürel Miras Başkentliği unvanlarını taşımaktadır.[7]\n" +
                            "\n" +
                            "Türk Hava Yolları'nın Airbus A330-200 tipi uçağı, TC-JNG, de 'Eskişehir' adını taşımaktadır. Eskişehir, İç Anadolu Bölgesi'nin kuzeybatısında yer almaktadır. İl merkezinin kuzeyinde Mihalgazi ve Sarıcakaya, doğusunda Alpu ve Ankara, güneyinde Mahmudiye, Seyitgazi ve Afyon, batısında ise İnönü ve Kütahya sınırları ile çevrilidir. "
                    27 -> bilgiler.text = "Gaziantep \n\nGaziantep ya da eski ve halk arasındaki kısa adıyla Antep (Osmanlıca: عینتاب Ayntab) Türkiye'nin bir ili ve en kalabalık dokuzuncu,[3] şehir merkez nüfusuyla en kalabalık 6. şehri. 2022 itibarıyla 2.154.051 nüfusa sahiptir.[2] Akdeniz ile Güneydoğu Anadolu Bölgesi'nin kesişme noktasında bulunan Türkiye'nin önemli şehirlerinden Gaziantep; sanayi ve gelişmişlik bakımından ilk sıralarda yer alır. Eğitim, ticaret ve sanayi şehridir. Hâlâ yaşanılan en eski kentlerinden biridir.[4] Bunların yanında Gaziantep, Türkiye sanayisi ve ticaretinde de çok önemli bir yer tutar. Bunun sebepleri arasında Gaziantep'in Anadolu ile Orta Doğu arasında bir konumda bulunması ve liman kentlerine yakınlığı sayılabilir. Gaziantep'in simgeleri arasında Gaziantep Kalesi sayılabilir.\n" +
                            "\n" +
                            "Gaziantep'te çok sayıda pınar bulunmasına karşın hiç doğal göl bulunmamaktadır. Bu yüzden şehrin birçok yerine yapay göller ve barajlar inşa edilmiştir. İlin en önemli akarsuyu Fırat Nehri ve kollarıdır. Gaziantep ilinde çok az doğal orman bulunmaktadır. İldeki toprakların sadece %14'ü ormanlık alanlarla kaplıdır. Bu ormanlarda özellikle meşe ve kızılçam ağaçları hâkimdir. Meşe ormanlarının hepsi bozuk olup koruma altındadırlar. Kızılçam ormanlarının çoğunluğu yapay ormandır. Gaziantep ilinin batı ve kuzey çevreleri ormanlık, bozkır ve meralarla çevrilidir. İlin topraklarının yüzde 60'ı tarıma elverişlidir. Bu kısım, tarlalar, zeytin, Antep fıstığı, meyve ve sebze bahçeleri ile bağlarla kaplıdır.[5]\n" +
                            "İldeki başlıca dağlar, ilin batısındaki Nur Dağları ile Sof Dağları'dır. Nur ve Sof Dağları arasındaki bölge levha hareketleri sonucu oluşmuş bir çöküntüdür. İldeki en yüksek dağ ise 1496 metre yüksekliği ile Büyük Sof Dağı'dır. İldeki başlıca ovalar ise İslahiye, Barak, Araban ve Tilbaşar ovalarıdır. Gaziantep ilinde Nurdağı ve İslahiye 1. derece, Yavuzeli ve Araban 2. derece, Oğuzeli, Nizip ve Karkamış ise 3. derece deprem bölgesidir.[6] "
                    28 -> bilgiler.text = "Giresun\n\nGiresun, fındığı ile tanınan ve Karadeniz Bölgesi'nin doğusunda yer alan il. Kirazın bütün dünyaya buradan yayıldığı kabul edilir. Karadeniz'e kıyısı olan Giresun doğudan batıya Trabzon, Gümüşhane, Erzincan, Sivas ve Ordu illeriyle çevrilidir. Trafik numarası 28'dir. Yerli halkın çoğunluğunu Çepniler oluşturur. 1500'lü yıllardaki Osmanlı Tahrir Defterlerinde yöreye Vilayet-i Çepni de denmektedir.\n" +
                            "\n" +
                            "Giresun ili, Mustafa Kemal'in 19 Mayıs 1919'da Samsun'a çıktıktan sonraki dönemde olan kişisel muhafızlarının (Topal Osman ve Silah Arkadaşları) memleketi olan bir ildir. Şehir, Aksu ve Batlama vadileri arasında denize doğru uzanan bir yarımada üzerinde kurulmuştur, tam karşısında Karadeniz'in bir adası olan Giresun Adası (Aretias) vardır. Giresun ili 1920 yılına kadar Trabzon iline bağlı kalmış, bu tarihte müstakil sancak, 1923 yılında ise il olmuştur. 1923 yılında Giresun ili; merkez, Tirebolu ve Görele ilçesi ile bunlara bağlı Bulancak, Keşap ve Espiye bucaklarından ibaretti. 1933 yılında Şebinkarahisar'ın illiğinin kaldırılması ile Şebinkarahisar ve Alucra ilçeleri de Giresun'a bağlanmıştır. 1934 yılında Bulancak, 1945 yılında Keşap, 1957 yılında Espiye, 1958 yılında Dereli, 1960 yılında Eynesil, 1987 yılında Piraziz ve Yağlıdere, 1992 yılında Çanakçı, Güce, Doğankent ve Çamoluk ilçelerinin kurulması ile ilçe sayısı 16 olmuştur.  "
                    29 -> bilgiler.text = "Gümüşhane\n\nGümüşhane, Doğu Karadeniz Bölgesi'nde yer alan, Türkiye'nin bir ilidir. Doğuda Bayburt, batıda Giresun, kuzeyde Trabzon ve güneyde Erzincan ile komşudur.\n" +
                            "\n" +
                            "Gümüşhane ili nüfusu: 141.702'dür. Bu nüfusun % 75' i şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 6.668  km2'dir. İlde  km2'ye 21 kişi düşmektedir. (Bu sayı Merkez ilçede 27’dir.) 2020 yılında İlde yıllık nüfus  % 13,87 azalmıştır.[2]\n" +
                            "\n" +
                            "2020 TÜİK verilerine göre 6 İlçe, 14 belediye, bu belediyelerde 76 mahalle, ayrıca 318 köy bulunmaktadır.[2]  "
                    30 -> bilgiler.text = "Hakkari \n\nHakkâri, Türkiye'nin güneydoğusunda yer alan il ve en kalabalık altmış ikinci şehri. TÜİK verilerine göre 2021 sonu itibarıyla 278.218 kişilik nüfusa sahiptir.[2] Tamamı Doğu Anadolu Bölgesi'nin doğusunda yer alır. Yüzölçümü bakımından Türkiye'nin kırk sekizinci büyük ilidir. Güneyinde Irak, batısında Şırnak, kuzeyinde Van, doğusunda ise İran vardır.\n" +
                            "\n" +
                            "Hakkâri ili nüfusu: 278.218'tür. (2021 sonu). İlin yüzölçümü 7.095 km2dir. İlde km2ye 40 kişi düşmektedir. 5 ilçe, 8 belediye, bu belediyelerde 56 mahalle, ayrıca 125 köy bulunmaktadır.[2] "
                    31 -> bilgiler.text = "Hatay\n\nHatay, Türkiye'nin Akdeniz Bölgesi'nde, Akdeniz'in doğu ucunda kıyıları olan bir ilidir. Hatay ilinin merkezi Antakya'dır.\n" +
                            "\n" +
                            "Hatay ili, 2021 yılında 1.670.712 kişiden oluşan bir nüfusa sahip.[2] Akdeniz'in doğu şeridinde 35° 52' - 37° 4' kuzey enlemleri ile 35° 40' - 36° 35' boylamları arasında yer alan Hatay'ın doğusunda ve güneyinde Suriye, batısında Akdeniz, kuzeybatısında Adana, kuzeyinde Osmaniye ve kuzeydoğusunda Gaziantep bulunur.    "
                    32 -> bilgiler.text = "Isparta \n\nIsparta, Isparta ilinin merkez ilçesidir. Şehir, yöreye özgü el dokuması halılarıyla ve gül yetiştiriciliğiyle tanınmaktadır.Isparta, Türkiye'nin güneybatısında yer alan il. Akdeniz Bölgesi'nin kuzeyindeki Göller Yöresi'nde bulunur. "
                    33 -> bilgiler.text = "İçel (Mersin )\n\nMersin, Türkiye'nin bir ilidir. Dördü merkez ilçe olmak üzere 13 ilçesi vardır. Mersin Türkiye'nin Akdeniz Bölgesi'nde bulunan bir liman kentidir. Mersin Limanı Türkiye'nin en büyük limanları arasındadır. Şehirde turizm, sanayi, tarım, denizcilik gelişmiştir.\n" +
                            "\n" +
                            "Merkezdeki ilçeleri Akdeniz, Mezitli, Yenişehir, Toroslar; diğer ilçeleri ise Anamur, Aydıncık, Bozyazı, Silifke, Tarsus, Çamlıyayla, Erdemli, Gülnar ve Mut'tur. Toplam on üç ilçesi bulunmaktadır.[1] Büyükşehir belediyesi statüsü bulunmaktadır. Türkiye'nin güneyinde bulunan bir liman kentidir. Mersin Limanı Türkiye'nin en büyük limanları arasındadır.[2]\n" +
                            "\n" +
                            "Kentin kuzeyindeki Yumuktepe höyüğünde yapılan kazılarda birçok katman ortaya çıkarılmıştır. Bunların en eskisi, MÖ 6300'lere, en yenisi ise Selçuklu dönemine tarihleniyor. Kazılardan çıkarılan eserler, Mersin Arkeoloji Müzesi başta olmak üzere, Adana Arkeoloji Müzesi ve Tarsus Müzesi, Silifke Müzesi ve Anamur Müzesi'nde sergileniyor. Helenistik dönemde kentin ismi Zephyrion'du. Bugün kentin sınırları içinde kalan Mezitli'nin adı ise Soli'ydi. Ancak Arap akınları döneminde kent boşaldı. Mersin'in tarih sahnesine çıkışı 19. yüzyılın ortalarına rastlamaktadır. Bu dönemde henüz bir köy olan bölge, konar göçer bir Türkmen aşiretine ev sahipliği yapmış ve adını da bu aşiretten almıştır. Ayrıca Kapadokya bölgesinden gelen Rumlar kent nüfusuna hâkim hâle gelmişti ve 1850'de kentte 5.250 Ortodoks Rum'a karşılık 1.600 Müslüman yaşamaktaydı. Kentin kaderi özellikle Amerikan İç Savaşı sırasında dünyadaki pamuk kıtlığını gidermek amacıyla Çukurova'da gelişen pamuk üretimi ve bölgenin 1866'da demir yolu ağına bağlanması ile değişmiştir. Bu dönemde Mersin hızla, Çukurova'nın tarım ürünlerinin ihraç edildiği bir liman ve ticaret merkezi hâline gelmiştir. Şehrin bugünkü durumuna gelmesinde, şu anda azınlık olsalar da Hristiyan Levantenlerin önemi yadsınamaz. Şehirde hâlen Levantenlere ait iki katedral bulunmaktadır: Latin-İtalyan Katedrali ve Arap-Ortodoks Katedrali. Ayrıca şehrin kuzeyine Rumlar için bir kilise yapılması da gündemdedir.\n" +
                            "\n" +
                            "Tarihçe "
                    34 -> bilgiler.text = "İstanbul \n\nİstanbul (Türkçe telaffuz: [isˈtanbuɫ]  ( dinle)), Türkiye'de Marmara Bölgesi'nde yer alan şehir ve Türkiye'nin 81 ilinden biridir. Ülkenin nüfus bakımından en çok göç alan ve en kalabalık ilidir. Ekonomik, tarihî ve sosyo-kültürel açıdan önde gelen şehirlerden biridir.[7][8][9] Şehir, iktisadi büyüklük açısından dünyada 34. sırada yer alır. Nüfuslarına göre şehirler listesinde belediye sınırları göz önüne alınarak yapılan sıralamaya göre Avrupa'da birinci, dünyada ise altıncı sırada yer almaktadır.[10][11]\n" +
                            "\n" +
                            "İstanbul Türkiye'nin kuzeybatısında, Marmara kıyısı ve Boğaziçi boyunca, Haliç'i de çevreleyecek şekilde kurulmuştur. İstanbul kıtalararası bir şehir olup, Avrupa'daki bölümüne Avrupa Yakası veya Rumeli Yakası, Asya'daki bölümüne ise Anadolu Yakası veya Asya Yakası denir. Tarihte ilk olarak üç tarafı Marmara Denizi, Boğaziçi ve Haliç'in sardığı bir yarımada üzerinde kurulan İstanbul'un batıdaki sınırını İstanbul Surları oluşturmaktaydı. Gelişme ve büyüme sürecinde surların her seferinde daha batıya ilerletilerek inşa edilmesiyle dört defa genişletilen şehrin[12] 39 ilçesi vardır. Sınırları içerisinde ise büyükşehir belediyesi ile birlikte toplam 40 belediye bulunmaktadır.\n" +
                            "\n" +
                            "Dünyanın en eski şehirlerinden biri olan İstanbul, 330-395 yılları arasında Roma İmparatorluğu, 395-1204 yılları arasında Bizans İmparatorluğu, 1204-1261 yılları arasında Latin İmparatorluğu,1261-1453 yılları arasında tekrar Bizans İmparatorluğu ve son olarak 1453-1922 yılları arasında Osmanlı İmparatorluğu'na başkentlik yaptı.[13] Ayrıca İstanbul, Hilâfetin Osmanlı İmparatorluğu'na geçtiği 1517'den kaldırıldığı 1924'e kadar İslam dünyasının da merkezi oldu.[14]\n" +
                            "\n" +
                            "Son yıllarda ortaya çıkartılan arkeolojik bulgularla insanlık tarihine ilişkin önemli bilgiler elde edilmiştir. Yarımburgaz Mağarası'ndan çıkarılan taş aletlerle, ilkel insan izlerinin 400.000 yıl öncesine dayandığı ortaya çıkmıştır.[15][16][17][18] Anadolu Yakası'nda yürütülen kazı çalışmaları ve bunlara bağlı araştırmalar, şehirde tarım ve hayvancılığa dayalı ilk yerleşik insan topluluğunun MÖ 5500'lere tarihlenen Fikirtepe Kültürü olduğunu göstermiştir.[19] Bu arkeolojik bulgular yalnızca İstanbul'un değil, tüm Marmara Bölgesi'nin en eski insan izleridir.[19] İstanbul sınırları içinde kent bazında ilk yerleşimler ise Anadolu Yakası'nda Kalkedon; Avrupa Yakası'nda Byzantion'dur. Cumhuriyet dönemi öncesinde egemenliği altında olduğu devletlere yüzlerce yıl başkentlik yapan İstanbul, 13 Ekim 1923 tarihinde başkentin Ankara'ya taşınmasıyla bu özelliğini yitirmiş; ancak ülkenin ticaret, sanayi, ulaşım, turizm, eğitim, kültür ve sanat merkezi olmaya devam etmiştir.[20]\n" +
                            "\n" +
                            "Karadeniz ile Marmara Denizi'ni bağlayan ve Asya ile Avrupa'yı ayıran İstanbul Boğazı'na ev sahipliği yapması nedeniyle, İstanbul'un jeopolitik önemi oldukça yüksektir.[21] Bugün tamamına yakını doldurulmuş olan ya da kaybolan doğal limanları vardır. Bu özellikleri yüzünden bölge toprakları üzerinde uzun süreli egemenlik anlaşmazlıkları ve savaşlar yaşanmıştır. Başlıca akarsular Riva, Kâğıthane ve Alibey dereleridir.[22] İl toprakları az engebelidir ve en yüksek noktası Kartal ilçesindeki Aydos Tepesi'dir.[22] İldeki başlıca doğal göller Büyükçekmece, Küçükçekmece ve Durusu gölleridir.[22] İl ve yakın çevresinde, Karadeniz ile Akdeniz makro iklimleri arasında geçiş özellikleri görülür.[22] Hava sıcaklıkları ve yağış ortalamaları düzensiz; bitki örtüsü dengesizdir.[22] "
                    35 -> bilgiler.text = "İzmir\n\nİzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan önde gelen şehirlerden biridir. Nüfusu 2022 itibarıyla 4.462.056 kişidir. Yüzölçümü olarak ülkenin yirmi üçüncü büyük ilidir.[6][7] Etrafı Aydın, Balıkesir, Manisa illeri ve Ege Denizi ve Ege Adaları ile çevrilidir.[8]\n" +
                            "\n" +
                            "İzmir, uzun ve dar bir körfezin başında yer almaktadır. İzmir Limanı, Türkiye'nin en büyük yedinci limanıdır. İzmir'in batısında denizi, plajları ve termal merkezleriyle Urla Yarımadası uzanır. Şehir, her yıl İzmir Enternasyonal Fuarı'nı düzenleyen önemli bir fuar merkezidir.  "
                    36 -> bilgiler.text = "Kars \n\nKars (Ermenice: Կարս veya Ղարս Gars, Azerice: Qars, Kürtçe: Qers, Rusça: Карс Kars), Kars ilinin merkez ilçesidir. Türkiye'nin rakımı en yüksek il merkezlerinden biri olan, köyleri ile birlikte nüfusu 100 bini aşan (Şehir merkezi: 90.523, toplam: 118.201) şehirlerinden biridir. Merkez ilçeye bağlı, 23 mahalle ve 72 köy bulunmaktadır. Çeşitli etnisitelerin birlikte yaşadığı il merkezinde kültürel farklılıklardan ve zenginliklerden bahsetmek mümkün olup kozmopolit bir yapı söz konusudur.[1] Kars, Kültür ve Turizm Bakanlığının 2023 yılı için Türkiye Turizm Stratejisi 2023 ve Turizm Stratejisi Eylem Planı kapsamına alınan 15 il merkezinden birisidir. Bu proje ile hedeflenen, il merkezlerini \"Kültür Turizmi Geliştirilecek Marka Kentler\" ilan edip gelişmelerini sağlamaktır.[2]\n" +
                            "\n" +
                            "Kars, geçmişte Bagratlı Krallığı'na[3] ve Cenub-u Garbi Kafkas Hükûmeti'ne[4] (Güneybatı Kafkasya Cumhuriyeti) başkentlik yapmış bir sınır şehridir. Bu özelliği ile Türkiye'de herhangi bir ülkeye başkentlik yapmış ender şehirlerden birisidir.\n" +
                            "\n" +
                            "Türkiye'nin Kafkasya'ya açılan kapısı konumundaki bu şehir, Kafkas Üniversitesinin açılmasıyla hızla gelişmeye başlamış ve zaman içinde bir öğrenci kenti durumuna gelmiştir. Ayrıca şehir merkezine altı kilometre uzaklıktaki havalimanı sayesinde de bölgesinde ulaşım ağının kesiştiği bir noktada yer alır. Bunun dışında kara ve demir yolu ağlarıyla ülkenin diğer yerleşim birimlerine ulaşımda da bir sorun yoktur.\n" +
                            "\n" +
                            "Kentte 2004 yılından bu yana Azerbaycan Başkonsolosluğu bulunmaktadır.[5] "
                    37 -> bilgiler.text = "Kastamonu\n\nKastamonu, Türkiye'nin kuzey kesiminde, Karadeniz Bölgesi'nde yer alan ildir. İlin komşularını (kuzeyden saat yönünde ilerlendiğinde) Sinop, Çorum, Çankırı, Karabük ve Bartın illeri oluşturmakta olup, ilin ayrıca kuzeyde Karadeniz'e kıyısı bulunmaktadır. İlin merkezi aynı isimli Kastamonu şehridir.  "
                    38 -> bilgiler.text = "Kayseri \n\nKayseri (Yunanca: Καισάρεια, romanize: Kaisareia), Türkiye'nin bir ilidir.[4] Türkiye'nin toplam nüfus bakımından en kalabalık 14. şehri olup yüzölçümü olarak Türkiye'nin en büyük 8.[5] [6][daha iyi kaynak gerekli]ilidir. İç Anadolu’nun büyük ticaret ve sanayi merkezidir.\n" +
                            "\n" +
                            "Orta Kızılırmak Bölümünde, Erciyes Dağı'nın eteklerinde bir ildir. Kuzey ve kuzeybatıda Yozgat, kuzey ve kuzeydoğuda Sivas, doğuda Kahramanmaraş, güneyde Adana, güneybatıda Niğde, batıda ise Nevşehir illeriyle çevrilidir. Dünyanın en eski şehirlerinden biri olan Kayseri (eski Mazaka, Ermenice: Մաժաք Mažak), klasik çağlarda Kapadokya adı verilen bölgededir. Kızılırmak'ın güneyinde bulunan bu bölge, Tuz Gölü'nden Fırat Nehri' ne kadar uzanır. İpek Yolu buradan geçer. Bölge, pek çok uygarlığın beşiği olmuştur.  "
                    39 -> bilgiler.text = "Kırklareli\n\nKırklareli ya da eski adıyla Kırk Kilise[2] (Yunanca: Σαράντα Εκκλησιές Saranta Eklesies; Bulgarca: Лозенград Lozengrad), Kırklareli ilinin merkezi olan şehirdir.\n" +
                            "\n" +
                            "Kırklareli tarih boyunca konumu itibarıyla birçok antik yerleşim merkezine sahip bir ildir. Buzul çağı sonlarında uzunca bir süre sular altında kaldığı anlaşılan Kırklareli ve civarında insana dair ilk maddî belgeler neolitik dönem özelliklerini vermektedir. Daha sonra bilinen ilk yerleşik kabilelerden ismini alan Trakya, Kırklareli de dahil olmak üzere Roma dönemi ortalarına kadar kısmen veya tamamen bağımsızlıklarını küçük birer krallık veya prenslik olarak devam ettirebilmişlerdir.\n" +
                            "\n" +
                            "Bir geçiş bölgesi olması nedeniyle Roma ve Bizans dönemlerinde pek çok istilalara uğrayan Kırklareli ilk defa I. Murat zamanında 1363 yılında Osmanlıların eline geçmiştir. Bu tarihten itibaren uzunca bir barış süreci yaşayan Kırklareli Balkan Savaşı ve I. Dünya Savaşı sıralarında Bulgar ve Yunan işgaline maruz kalarak büyük eziyet ve sıkıntılar yaşadıktan sonra 10 Kasım 1922’de nihai özgürlüğüne kavuşmuştur.  "
                    40 -> bilgiler.text = "Kırşehir\n\nKırşehir, Kırşehir ilinin şehir merkezidir. 1941 yılında Ankara'da toplanan I. Coğrafya Kongresi'nde bu bölgeye ve bölgenin Orta Kızılırmak Bölümü'ne alındı. Özellikle son yıllarda köylerin göç vermesiyle nüfus merkez ilçede yoğunlaşmıştır. 1927'de 13.000 olan 1990'da 73.538'e, 2000'de 88.105'e çıkmıştı. 2010'da 110.000 olan merkez ilçe nüfusu 2021 itibarıyla 160.737'dir.\n" +
                            "\n" +
                            "Kırşehir doğu ve güneydoğuda Nevşehir, güneyde Aksaray, kuzeybatıda Kırıkkale, kuzeydoğu ve doğuda Yozgat, batıda Ankara ile çevrilidir. Kabaca bir paralel kenarı andıran il topraklarını güney ve güneybatıda Kızılırmak, batı da ve kuzeybatıda Kılıçözü Deresi, kuzey ve kuzeydoğuda Deliceırmak sınırlar. İl topraklarının genişliği ülke topraklarının binde 8'i, İç Anadolu topraklarının yüzde 2,9'u kadardır.\n" +
                            "\n" +
                            "İlin yüzölçümü 6.570 kilometrekaredir. Bu yüzölçümün ilçelere göre dağılımı şöyle:\n" +
                            "\n" +
                            "Akçakent 370 Akpınar 582 Boztepe 747 Çiçekdağı 891 Kaman 1284 Kırşehir Merkez 1719 Mucur 992 km²'dir.\n" +
                            "\n" +
                            "Orta Kızılırmak Havzası'nda ve bölümünde yer alan Kırşehir il toprakları 39°41'- 39°48' kuzey enlemleri ile 33°25'-34°43' doğu boylamları arasında yer alır. Denizden 985 metre yükseklikte olan şehrin kuş uçuşu olarak gerçek uzaklığı Karadeniz'e (Sinop) 334 km, Akdeniz'e (Anamur Burnu) 362 km.\n" +
                            "\n" +
                            "Kırşehir, yönetim bakımından doğu ve güneydoğuda Nevşehir'in Kozaklı, Hacıbektaş ve Gülşehir; güneyden Aksaray'ın Ortaköy güney ve güneybatıda Ankara'nın Şereflikoçhisar ve Bâlâ; kuzeybatıda Kırıkkale'nin Keskin ve Delice; kuzey ve kuzeydoğuda Yozgat'ın Boğazlıyan ve Yerköy ilçeleri ile çevrilmiştir.\n" +
                            "\n" +
                            "Kent, Kayseri ve Nevşehir ile birlikte Kapadokya diye anılan üçgenin kuzeyindedir. Çoğu ya kaybolmuş ya da bilinmeyen eserlerin bulunduğu Kapadokya'nın merkezi ise Kırşehir'dir. Kapadokya Bölgesi, Kayseri merkez olmak üzere Tuz Gölü'nün doğusundan, güneyde Doğu Toroslar; kuzeyde Kırşehir ve Sivas'ın önemli bir kısmını içine alarak Malatya'ya kadar uzanır. Pers dilinde \"Katpatukya\" olarak adlandırılan Kapadokya'nın sözlük anlamı \"Güzel Atlar Ülkesi\"dir. Burası binlerce yıl, birçok devlete kucak açmıştır. Kimlerin ne kadar zaman önce buralara geldiği belli değildir.\n" +
                            "\n" +
                            "Şehirdeki tek üniversite Ahi Evran Üniversitesi'dır. Üniversitede tıp fakültesi ile birlikte birçok fakülte ve yüksek okul bulunmaktadır.\n" +
                            "\n" +
                            "Termal yönden zengin kaynaklara sahip bir coğrafyada yer alan şehir doğu-batı, kuzey-güney akslarının kesişim noktasındadır. Türkiye'nin tek yerli sermayeli lastik fabrikası Petlas burada üretim yapmaktadır.\n" +
                            "\n" +
                            "Kırşehir, Anadolu bozkırının ortasında kültür ve sanat merkezi özelliğine sahiptir. Bugün bile hayranlık uyandıran Ahilik felsefesinin doğup yayıldığı Kırşehir, göz kamaştırıcı bir kültür varlığına sahiptir. 13. yüzyılda Türkçeyi büyük bir inançla savunup Türkçe şiirler yazarak Türk edebiyatının ölümsüz isimleri arasına katılan Aşık Paşa'yı; gökbilim, İslâm hukuku, felsefe-tasavvuf bilgini Caca Bey'i ve daha nicelerini yetiştirmiş bir ildir. Bunların dışında birçok ses sanatçısı, gazeteci ve bilim insanı da Kırşehir'de yetişmiştir.\n" +
                            "\n" +
                            "Kırşehir 2019 yılında Sanayi ve Teknoloji Bakanlığı'na bağlı Ahiler Kalkınma Ajansı ve Kırşehir Belediyesi'nin girişimleri ile UNESCO Yaratıcı Şehirler Ağına Müzik alanında dahil olmuştur. Türkiye'den müzik alanında bu ağa dahil olan ilk ve tek şehir olma özelliğini de taşımaktadır.  "
                    41 -> bilgiler.text = "Kocaeli\n\nKocaeli, Türkiye'nin bir ili ve en kalabalık onuncu şehridir. Şehir, ülkenin en büyük sanayi ve ticaret kentlerinden biridir. Kocaeli; SEGE-2011 sıralamasına göre İstanbul, Ankara ve İzmir'den sonra en gelişmiş şehirdir. 2022 itibarıyla 2.033.441 kişilik nüfusa sahiptir.[3] Adını 1320 yılında İzmit yöresini fetheden Akça Koca'dan almaktadır. İstanbul, Bursa, Sakarya, Yalova illeriyle komşudur.  "
                    42 -> bilgiler.text = "Konya\n\nKonya, Türkiye'nin yüzölçümü bakımından en büyük ili ve en kalabalık altıncı şehridir. 31 ilçeden oluşur. Konya il nüfusu 2021 yılında 2.277.017'ydi,[1] trafik plaka numarası 42'dir.[4] 1875'te kurulan Konya Belediyesi, 1987'de çıkarılan 3399 sayılı yasa gereğince \"büyükşehir\" statüsüne kavuşmuş olup 1989'dan beri belediye hizmetleri bu statüye göre yürütülmektedir. 2014'te 6360 sayılı kanun ile büyükşehir belediyesinin sınırları il mülki sınırları oldu.\n" +
                            "\n" +
                            "Ekonomik açıdan Türkiye'nin gelişmiş kentlerinden biri olan Konya doğal ve tarihsel zenginlikleriyle de önem taşır. Dünyanın en eski yerleşimlerinden biri olan Çatalhöyük, 2012 yılında UNESCO Dünya Miras Listesi'ne alınmıştır. Şehir Anadolu Selçukluları’nın ve Karamanoğulları’nın başkentliğini yapmıştır. Türkiye'nin en önemli sanayi kentlerinden birisidir. Anadolu Kaplanları'ndandır. Şehrin futbol takımı Konyaspor'dur. Yöresel yemekleri etliekmek, bamya çorbası, Mevlana böreği, yağ somunu, tirit, Konya pilavı, sac arası ve fırın kebabı'dır. Konya’nın simgeleri Mevlana Müzesi (Kubbe-i Hadrâ), çift başlı kartal'dır.  "
                    43 -> bilgiler.text = "Kütahya \n\nKütahya, Türkiye Cumhuriyeti'nin Ege Bölgesi'nde yer alan bir ilidir.\n" +
                            "\n" +
                            "Kütahya ili nüfusu: 576.688'dir. Bu nüfusun %78,3'ü şehirlerde yaşamaktadır (2020 sonu). İlin yüz ölçümü 11.632 km2'dir. İlde km2'ye 50 kişi düşmektedir.[4]\n" +
                            "\n" +
                            "2021 TÜİK verilerine göre 13 ilçe, 28 belediye, bu belediyelerde 222 mahalle, ayrıca 546 köy bulunmaktadır.[4] "
                    44 -> bilgiler.text = "Malatya \n\nMalatya (Ermenice: Մալաթիա Malat'ia; Kürtçe: Meletî; Grekçe: Μελιτηνή Melitini), Türkiye'nin büyükşehir statüsündeki[3] otuz ilinden biridir. Doğu Anadolu Bölgesi'ndeki Yukarı Fırat Bölümü'nde yer alır. 13 ilçesi ve 718 mahallesi bulunan[4] 2021 TÜİK verilerine göre Malatya, 808.692 kişilik nüfusuyla Türkiye'nin yirmi sekizinci en yüksek nüfuslu ilidir.[5] Doğusu Elazığ ve Diyarbakır, güneyi Adıyaman ve Kahramanmaraş, batısında Kayseri, kuzeyi ise Sivas ve Erzincan ile çevrilidir. İlk olarak Hitit döneminde kurulmuştur. O günden bugüne el değiştirerek yıkılıp yeniden yapılarak günümüze kadar gelmiştir.[6]\n" +
                            "\n" +
                            "Malatya, kayısı diyarı olarak bilinir. İlde yetişen kayısılar, dünya genelinde ünlüdür ve kuru kayısı üretiminin %80'ini Malatya Ovası’nda bulunan kayısı bahçeleri sağlar.[7] Büyükşehir yasası ile 2014 yerel seçimlerinin ardından büyükşehir statüsüne kavuşmuştur. Aynı zamanda Malatya 2 Cumhurbaşkanı çıkarmış tek şehirdir, bu kişiler, İsmet İnönü ve Turgut Özal'dır. "
                    45 -> bilgiler.text = "Manisa \n\nManisa, Türkiye'nin bir ili ve Ege Bölgesi'nin en büyük ikinci şehridir. Türkiye'nin en kalabalık on dördüncü şehri olan Manisa'nın 2022 TÜİK verilerine göre nüfusu 1.468.279 kişidir.[3] Anadolu Yarımadası'nın batısında, Ege Bölgesi'nin ortasında yer alır. Doğudan Uşak ve Kütahya, güneyden Aydın ve Denizli, kuzeyden Balıkesir ve batıdan İzmir ile komşudur. 27°08’ ve 29°05’ doğu boylamları ile 38°04’ ve 39°58’ kuzey enlemleri arasında yer alır. 17 ilçesi vardır. Toplam nüfus bakımından İzmir'den sonra Ege Bölgesi'nin ikinci büyük ili ve ticaret merkezidir. 2012 yılında çıkarılan 6360 sayılı kanun ile büyükşehir olmuştur.[7]\n" +
                            "\n" +
                            "\"Şehzadeler Şehri\" olarak da adlandırılan yerleşim; mesir macunu, sultaniye üzümü ve Manisa Tarzanı ile tanınır. Antik Çağ'da \"Magnesia\", Roma İmparatorluğu döneminde tam ismiyle \"Magnesia ad Sipylum\" olarak anılmıştır.\n" +
                            "\n" +
                            "Şehir, Spil Dağı'nın eteklerinde kurulmuştur. Gediz Nehri'nin büyük bir bölümü il sınırları içerisinden geçmektedir. "
                    46 -> bilgiler.text = "Kahramanmaraş\n\nKahramanmaraş, halk arasındaki kısa adıyla Maraş (Yunanca: Καχραμανμάρας Ermenice: Մարաշ Maraş), Türkiye Cumhuriyeti'nin Akdeniz Bölgesi'nde bulunan bir ildir. Maraş Muhaberesi sırasında işgale direnişi nedeniyle Türkiye Büyük Millet Meclisi tarafından 05 Nisan 1925 tarihinde şehre İstiklâl Madalyası verilmiştir. Doğusunda Malatya ve Adıyaman, batısında Kayseri ve Adana, güneyinde Gaziantep ve Osmaniye, kuzeyinde Sivas illeri yer almaktadır. Maraş olan adı, 7 Şubat 1973 tarihinde Türk Kurtuluş Savaşı'nın başarı ile sonuçlanmasında dolayı adı Kahramanmaraş olarak değiştirilmiştir.\n" +
                            "\n" +
                            "Geç Hitit şehri olan Gurgum’un bulunduğu yerde kurulmuştur. Sistematik bir kazı yapılmamış olmasına rağmen birçok Hitit anıtı bulunmuştur.[2]\n" +
                            "\n" +
                            "Osmanlı seyyahı Evliya Çelebi, seyahatnamesinde Maraş halkı için, \"kelimatları lisan-ı Türkidir ve ekseriya halkı Türkmendir\" der.[3] Maraş ve çevresi başta Oğuzların Avşar, Bayat ve Beğdili boyları çoğunlukta olmakla birlikte hemen hemen yirmi dört Oğuz boyunun tamamı mevcuttur.\n" +
                            "\n" +
                            "2012'de çıkarılan 6360 sayılı kanun ile büyükşehir olmuştur. Aynı zamanda il sınırları içerisinde bulunan Afşin - Elbistan A, B, C termik santralleri sayesinde Kahramanmaraş, Türkiye'nin elektrik ihtiyacının %14'ünü tek başına karşılamaktadır.[4]\n" +
                            "\n" +
                            "Dövme Dondurması, tarhanası ve biberi şehrin önemli tescilli gıdalarıdır. 2021 itibarıyla %1,22 artarak 1.168.163 nüfusa ulaşmıştır.[5]  "
                    47 -> bilgiler.text = "Mardin  \n\nMardin, Türkiye'nin büyükşehir statüsüne giren bir ili ve en kalabalık yirmi altıncı şehridir. 2021 yılı TÜİK verilerine göre nüfusu 862.757’dir.[2] Güneydoğu Anadolu Bölgesi'nin Dicle Bölümü'nde yer alır. Suriye ile sınır komşusudur.\n" +
                            "\n" +
                            "Şehirde uluslararası kuruluşlarca kültür mirası kabul edilmiş, koruma altına alınmış tarihi yapılar mevcuttur. Mardin farklı dini inanışlar paralelinde, sanatsal açıdan da tarihi değeri olan camiler, türbeler, kiliseler, manastır ve benzeri dini eserler barındırmaktadır. Mardin, İpek Yolu güzergâhında olup, ilde beş han ve bir kervansaray mevcuttur."
                    48 -> bilgiler.text = "Muğla\n\nMuğla, Türkiye'nin bir ili ve en kalabalık yirmi dördüncü şehridir. 2020 itibarıyla 1.021.773[2] nüfusa sahiptir. Ege Bölgesi'nde, topraklarının küçük bir kısmı Akdeniz Bölgesi içine giren, Ortaca, Dalaman, Köyceğiz, Fethiye, Marmaris, Milas, Datça ve Bodrum gibi tatil yöreleri ile ünlü bir yerleşim yeridir. İlde 13 ilçe bulunur.  "
                    49 -> bilgiler.text = "Muş \n\nMuş (Ermenice: Մուշ, Kürtçe: Mûş), Muş ilinin merkezi olan ve ile ismini veren şehirdir. Ayrıca Muş ilinin merkez ilçesidir.\n" +
                            "\n" +
                            "Muş şehri, Muş ilinin batısında yer almaktadır. Çavuş Dağı'nın kuzeydoğu eteklerinde kurulmuş olan kentin tarihsel çekirdeği kalenin çevresidir. İstasyonun yer aldığı Muş Ovası'na doğru sekiler halinde gelişen kentin eski ve yeni kısımları arasında 200 metre yükseklik farkı vardır.\n" +
                            "\n" +
                            "Muş Ovası'nın kenarında kurulan bu Doğu Anadolu Bölgesi şehri, lalesi ve üzümü ile tanınır. Kent ve daha çok il Selçuklu dönemi eserleri; Malazgirt Savaşı ve Alparslan ile özdeşleşmiştir.\n" +
                            "\n" +
                            "Muş şehri, 1929 yılında Bitlis vilayetinden ayrılarak müstakil bir il olarak, il merkezi konumu haline gelmiştir. 2008 yılı itibarıyla merkez nüfusu 70 bin dolaylarındadır. Coğrafi açıdan, Doğu Anadolu Bölgesi'nin Yukarı Murat-Van Bölümü içerisinde yer alır. Muş ili ve şehri ayrıca Doğu Anadolu Bölgesi Kalkınma Projesi içinde yer almaktadır[2].\n" +
                            "\n" +
                            "Muş Merkez ilçesi, kuzeyden Varto; doğudan Bulanık, Hasköy ve Korkut ile komşudur. Malazgirt ilçesi ile sınırı yoktur. Solhan, Kulp ve Hınıs ile de sınırdaştır. "
                    50 -> bilgiler.text = "Nevşehir\n\nNevşehir, Türkiye'nin İç Anadolu Bölgesinde yer alan bir ildir.\n" +
                            "\n" +
                            "Nevşehir, Muşkara adlı bir köy iken, şehir halini almaya başlamasından sonra, 18. yüzyılda Osmanlı Türkçesi'nde \"yeni kent\" anlamına gelen bugünkü adını almıştır.[3]\n" +
                            "\n" +
                            "Nevşehir, 6429 sayılı yasa ile 20 Temmuz 1954 tarihinde il haline getirildi. Kırşehir ve Kırşehir'e bağlı Mucur, Avanos, Hacıbektaş (1945'te ilçe oldu), Kayseri'ye bağlı Ürgüp (1935'te ilçe oldu), Niğde'ye bağlı Arapsun (1948'de Gülşehir adını aldı) Nevşehir'in ilçeleri haline getirildi. Kozaklı ve Hamamorta köyleri Avanos'a bağlı birer köy iken birleştirilerek 1954'te Kozaklı adıyla ilçe olarak Nevşehir'e bağlandı. Kırşehir 1957'de tekrar il yapıldı. Mucur ilçesi ile beraber Nevşehir'den ayrıldı. Daha önceleri Melegübü ismi ile anılan bir bucak merkezi olan Derinkuyu, 1 Nisan 1960'ta ilçe durumuna getirildi. Acıgöl kasabası ise 4 Temmuz 1987'de ilçe olmuştur.  "
                    51 -> bilgiler.text = "Niğde\n\nNiğde, Türkiye'nin İç Anadolu Bölgesi’nin güneydoğusunda ve Kapadokya bölgesinde yer alan merkezi Niğde kenti olan idari birimdir. Rakımı 1.229 m olan Niğde ilinin 2022 yılı itibarıyla nüfusu 363.725'dir.[4]\n" +
                            "\n" +
                            "Aksaray, Nevşehir, Kayseri ve Konya illerine komşu olan Niğde, güneyde Bolkar Dağları ile Mersin ilinden, güneydoğu ve doğudan Aladağlar’ın oluşturduğu doğal sınırlarla da Adana ilinden ayrılır. Genel olarak İç Anadolu Bölgesi'nde olan ilin Çamardı ve Ulukışla ilçeleri Akdeniz Bölgesi'nde yer almaktadır.\n" +
                            "\n" +
                            "Kenti turizm merkezi yapan termal kaynakları, ören yerleri, tarihî dokusu, doğal güzellikleri, dağ ve kış turizmi olanakları mevcuttur.[5][6] Aladağlar ve Ketençimen Yaylası kış turizmi yapılan bölgelerdir.[7]\n" +
                            "\n" +
                            "Halkın esas geçim kaynağı tarım ve hayvancılıktır. Elma ağacı sayısında Niğde ili ülke sıralamasında ilk sırada yer alır. Ülke genelinde patates üretiminin ise % 25'lik bölümü bu ilde üretilir. Ancak Niğde Merkez Organize Sanayi, Bor Deri Organize Sanayi, halı fabrikası ve diğer küçük sanayi kolları Niğde halkı için önemli istihdam alanlarıdır. Geleneksel el sanatları bakımından Niğde önemli bir ildir. Niğde ilinde üretilen halılar dünyanın birçok ülkesinde müşteri bulmaktadır. 1992 yılında kurulan üniversite, güncel adıyla Niğde Ömer Halisdemir Üniversitesi, personeli ve öğrenci sayısı ile kentin önemli hareketlilik unsurlarından biridir.  "
                    52 -> bilgiler.text = "Ordu\n\nOrdu, Türkiye'nin bir ili ve en kalabalık yirmi dokuzuncu şehridir. 2020 Yılı verilerine göre nüfusu 761.400'dür.[3] Karadeniz Bölgesinde Doğu Karadeniz bölümünde yer almaktadır. Ancak yeni oluşturulan ve bölgesel karışıklıkları ortadan kaldırmak için düzenlenen yeni bölgesel istatistiki düzenlemelerde Ordu ilinin tamamı Doğu Karadeniz topraklarında kaldı. İlin kuzeyinde Karadeniz, güneyinde Tokat ve Sivas illeri, batısında Samsun, doğusunda Giresun ili vardır. Büyükşehir statüsünde olan Ordu, 19 ilçeden oluşmaktadır. Yüzölçümü bakımından en büyük 57'nci ildir.\n" +
                            "\n" +
                            "Osmanlı döneminde, 1920 yılında, bağlı olduğu Trabzon vilayetinden ayrılmış, 4 Nisan 1920 tarihinde il statüsüne kavuşmuştur. 2020 yılında TÜİK verilerine göre 19 İlçe ve belediye, bu belediyelerde toplam 772 mahalle bulunmaktadır.[3] İl merkezinden doğuya gidildikçe  Gülyalı, batıya il yolundan 52-82 gidildikçe Perşembe, Karadeniz Sahil Yolu'ndan  / gidildikçe Fatsa, Ünye ilçelerine ulaşılır. Güneye giden en önemli yol; Ulubey, Gürgentepe, Gölköy, Mesudiye ilçelerinden geçer.  "
                    53 -> bilgiler.text = "Rize\n\nRize, Türkiye'nin kuzeydoğusunda yer alan ve Karadeniz'e sahili olan bir ildir. Karadeniz Bölgesi'nde yer alan Rize'nin, batısında Trabzon, doğusunda Artvin, güneybatısında Bayburt, güneyinde Erzurum illeri bulunur. Türkiye'nin en çok yağış alan ilidir[3]. En önemli ürünü çaydır. Rize'de yaz mevsimi ılık geçer. Sonbahar ve kış mevsimleri ise yağışlı geçer. Doğu Karadeniz Bölgesinde yer alan Rize, bölgenin en baskın karakteristik özelliklerini gösterir. Anadolu'nun diğer bölgelerinden coğrafi yapısıyla olduğu gibi kültürel yapısı ile de ayrılır. Dik yamaçlı vadileri, dağları, buzul gölleri, zümrüt yeşili yaylaları, kemer köprüleri, kaleleri ve coşkun akan dereleri ile bir turizm beldesidir.  "
                    54 -> bilgiler.text = "Sakarya \n\nSakarya, Türkiye'nin en kalabalık yirmi ikinci ilidir. İl ismini topraklarından geçen Sakarya nehri'nden almıştır. Sakarya İlinin merkezi Adapazarı'dır. Adapazarı 2021 yılında Danimarka'da aldığı ödül ile bisiklet şehri unvanını kazanmıştır.\n" +
                            "\n" +
                            "2021 yılı sonu TÜİK verilerine göre il nüfusu: 1.060.876 dur. 16 ilçe ve belediye, bu belediyelerde toplam 668 mahalle bulunmaktadır.[2]\n" +
                            "\n" +
                            "Marmara Bölgesi'nin Çatalca-Kocaeli Bölümü'nde yer alır.\n" +
                            "\n" +
                            "Sakarya'nın kuzeyinde Karadeniz, batısında Kocaeli, Bursa, doğusunda Düzce ve güneyinde de Bolu ile Bilecik bulunmaktadır. Sakarya Nehri, Sakarya'nın Karasu ilçesinde Karadeniz'e dökülür.\n" +
                            "\n" +
                            "Sakarya ekonomisinde tarımın önemli bir yeri vardır. Hendek, Karasu ve Kocaali ilçelerinde fındık yetiştiriciliği mevcuttur.[3] Ayrıca mısır tarımı da yapılmaktadır. Sakarya'da sanayi il merkezi Adapazarı yakınlarında yakınlarında gelişmeye başlamıştır. Son yıllarda kurulan sanayi kuruluşları bu sanayileşmeyi daha da artırmıştır. Sakarya, bir milyona yaklaşan toplam nüfusuyla İstanbul, Bursa, Kocaeli ve Balıkesir'in ardından Marmara Bölgesi'nin en büyük beşinci ilidir "
                    55 -> bilgiler.text = "Samsun \n\nSamsun, Türkiye'nin büyükşehir statüsündeki otuz ilinden biridir. Karadeniz Bölgesi'ndeki Orta Karadeniz Bölümü'nde, Türkiye coğrafyasının en kuzeyinde merkezî bir noktada yer alır. On yedi ilçesi ve 1.247 mahallesi bulunan Samsun, 1.371.274 kişilik nüfusuyla bölgenin en yüksek, Türkiye'nin ise on altıncı en yüksek nüfuslu ilidir. Doğusunda Ordu, güneyinde Tokat ve Amasya, batısında ise Çorum ve Sinop illeri ile çevrili olup kuzeyinde Karadeniz bulunur. Karadeniz Bölgesi'nin eğitim, sağlık, sanayi, ticaret, ulaşım ve ekonomi açılarından en gelişmiş şehri olan Samsun kalkınmada birinci derecede öncelikli yörelerden biridir.\n" +
                            "\n" +
                            "Yerleşim geçmişi MÖ 60.000 yılına dek uzanan Samsun'da varlığı bilinen en eski halk MÖ 12. yüzyıla kadar burada bulunan Kaşkalardır. Kaşkaların ardından Hitit dönemini yaşayan şehir, MÖ 1182 ile MÖ 546 yılları arasında birkaç kez el değiştirmiş ve devamında Pers hâkimiyetine girmiştir. Perslerin ardından Makedonya, Pontus, Roma, Bizans egemenliği gören Samsun, bunların ardından bir Ceneviz kolonisi hâline gelmiştir. Bu dönemde Dânişmendliler Beyliği tarafından kuşatılan şehir alınamamış ve şehrin hemen yanına \"Müslüman Samsun\" adıyla bilinen yeni bir şehir kurulmuştur. I. Mehmed dönemine dek iki Samsun şehri de varlığını sürdürmüş, bu dönemde her iki şehir de Osmanlı Devleti topraklarına katılarak birleştirilmiştir. 1422-1428 yılları arasında Kubadoğulları eline geçen Samsun, 1923 yılında Türkiye Cumhuriyeti'nin ilânına dek Osmanlı hakimiyetinde kalmıştır. Türkiye'nin kurulmasına dek uzanan 19 Mayıs 1919'da Mustafa Kemal'in Samsun'a çıkışıyla başlayan sürecin başlangıç durağı olması nedeniyle özel bir konumu bulunan Samsun 19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı'na ev sahipliği yapmaktadır. Buna izafeten resmî mahiyete sahip \"Güneşin Doğduğu Şehir\" sloganıyla tanıtılmakta, Samsun 19 Mayıs Marşı ise Samsun'un resmî marşı mahiyeti taşımaktadır. Öte yandan \"Karadeniz'in Başkenti\" ve \"Atatürk'ün Şehri\" olarak da anılmaktadır.\n" +
                            "\n" +
                            "9.725 km² alanda kurulu olan Samsun coğrafyasının %45'ini dağlar, %37'sini platolar, %18'ini ise ovalar meydana getirmekte olup en yüksek noktası 2.062 m'lik Akdağ'dır. Sahil şeridinde tipik Karadeniz ikliminin görüldüğü ilin iç kısımlarına doğru karasal iklim ağırlık kazanmakta olup ortalama yıllık sıcaklık 14,5 °C'dir. Su varlığı açısındansa özellikle Kızılırmak ve Yeşilırmak önemli nehirler olup oluşturdukları deltalar ile yoğun tarımsal faaliyetlerin sürdürülmesini sağlamaktadırlar.\n" +
                            "\n" +
                            "Cumhuriyetin ilk yıllarında ekonomisi tarım ve hayvancılık temelli olan ilin topraklarının %47'si hâlen tarım amaçlı kullanılsa da günümüzde ekonomik etkinlik büyük oranda ticaret ve sanayiye dayalı olup tarım ve hayvancılığın ağırlığı giderek azalmaktadır. Karayollarıyla Karadeniz Bölgesi'ni İç Anadolu Bölgesi ve Doğu Anadolu Bölgesi'ne bağlayan Samsun aynı zamanda bir liman şehri ve geniş hinterlandı ile bir lojistik noktasıdır. Samsun ve civarındaki kamu ile özel sektör yatırımları zaman içerisinde başka illerden nüfus göçünü teşvik etmiş olup 1927 yılındaki cumhuriyet döneminin ilk nüfus sayımından günümüze nüfusu %394 oranında artmıştır. Aldığı göçler nedeniyle karmaşık bir folklorik yapısı bulunan Samsun'da dil, halk oyunu ve yemek gibi halk kültürüne dair alanlarda bu yapısı hissedilmektedir. Şehir siyasi açıdan muhafazakârdır ve ağırlıklı olarak sağ partilere oy verilmektedir.\n" +
                            "\n" +
                            "Denizyolu, havayolu ve karayoluyla ulaşımın mümkün olduğu Samsun'a Samsun-Kalın demiryolu üzerinde yer alan yedi ilden ulaşım sağlanabilmektedir. Genellikle ticari amaçlarla ve karayolu aktarması için kullanılan denizyolunun haricinde gelişkin bir karayolu ağının bulunduğu il, dört farklı devlet yolu ile tüm Türkiye'ye ve Avrupa'ya bağlanmaktadır. Havayolu taşımacılığında ise Ankara, İstanbul, İzmir ve Antalya'nın yanı sıra dönemsel olarak Almanya, Avusturya ve Kuveyt'in toplam sekiz şehrine direkt uçuş gerçekleştirilmektedir. "
                    56 -> bilgiler.text = "Siirt\n\nSiirt, Türkiye'nin Güneydoğu Anadolu Bölgesi'nde yer alan bir ildir.\n" +
                            "\n" +
                            "Siirt ili nüfusu: 331.070'tir. Bu nüfusun %72,4'ü şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 5.718  km2'dir. İlde  km2'ye 58 kişi düşmektedir. (Bu sayı merkezde  268’dir.) İlde yıllık nüfus artışı % 0,24 olmuştur.[3] İl merkezinin denizden yüksekliği: 887 m.'dir.[4]\n" +
                            "\n" +
                            "2021 TÜİK verilerine göre 7 İlçe, 12 belediye, bu belediyelerde 63 mahalle, ayrıca 274 köy bulunmaktadır.[3]  "
                    57 -> bilgiler.text = "Sinop\n\nSinop, Türkiye'nin Karadeniz Bölgesi'nin batı karadeniz bölümünde bulunan Sinop ili'nin merkezi olan şehirdir. Karadeniz kıyısında, Boztepe Burnu'nun karayla birleşme noktasında yer alır. Sinop Kalesi, tarihi ve turizm açısından kentin en ilginç yeridir.[1] Türkiye'nin kuzeyde en uç noktası olan İnce burun Sinop ilinde'dir.   "
                    58 -> bilgiler.text = "Sivas \n\nSivas, Türkiye'nin İç Anadolu Bölgesi'nde yer alan Sivas ilinin merkez ilçesi ve bölgenin en eski ve önemli kentlerinden biridir. Doğusunda Hafik, güneyinde Ulaş ve Altınyayla, güneybatısında Şarkışla, batısında Yıldızeli ilçeleri; kuzeyden Tokat, Ordu, Giresun; doğudan Erzincan; güneyden Malatya, Kahramanmaraş ve Kayseri; batıdan da Yozgat illeriyle komşudur.\n" +
                            "\n" +
                            "Sivas merkez ilçe nüfusu 2021 istatistiklerine göre 388.079 kişidir.[1]  "
                    59 -> bilgiler.text = "Tekirdağ\n\nTekirdağ, Türkiye'nin bir ili ve en kalabalık yirmi ikinci şehridir. Tekirdağ nüfusu 2021 yılına göre 1.107.491'dir.[1] Marmara Bölgesi'nin Trakya yakasında bulunur; doğuda İstanbul, güneyde Marmara Denizi ve Çanakkale, batıda Edirne, kuzeyde Kırklareli ve kuzeydoğuda Karadeniz ile çevrilidir. 2012 yılında nüfusu 750.000'i geçen 14 adet il TBMM'de kabul edilen kanun ile büyükşehir statüsü kazandığı için Türkiye'nin 30 büyükşehrinden biridir. 30 Mart 2014'te yapılan yerel seçimlerin ardından resmen büyükşehir belediyeciliği ile yönetilmeye başlamıştır, hizmet sahası 6.190 km² olarak tüm il sınırlarıdır. Bu kanunla üç yeni ilçe kurulmuştur. Bunlar, Süleymanpaşa, Kapaklı ve Ergene'dir. Bu ilçelerle birlikte toplam ilçe sayısı on birdir.   "
                    60 -> bilgiler.text = "Tokat \n\nTokat, Türkiye'nin Karadeniz Bölgesi'nde yer alan ildir. Kuzeyde Samsun, kuzeydoğuda Ordu, doğu ve güneyde Sivas, güneybatıda Yozgat ve batıda Amasya illeriyle komşudur. İlçelerinden Yeşilyurt ve Sulusaray İç Anadolu Bölgesi'nde kalır.\n" +
                            "\n" +
                            "1943 yılında Erbaa, 1944'te Artova ve Turhal, 1954 yılında Almus, 1987 yılında Pazar ve Yeşilyurt, 1990 yılında ise Sulusaray ve Başçiftlik ilçeleri kurulmuştur.\n" +
                            "\n" +
                            "Şubat 2021 TÜİK verilerine göre merkez ilçeyle beraber 12 ilçe, 37 belediye ile bu belediyelerde 315 mahalle ve ayrıca 613 köy vardır.[2] İl merkezinin denizden yüksekliği 630 m.'dir.  "
                    61 -> bilgiler.text = "Trabzon\n\nTrabzon (Romeika: Τραπεζούντα, Trapezounta, Lazca: Ťrabuzeni), Türkiye'nin bir ili ve en kalabalık yirmi yedinci şehridir. Karadeniz Bölgesi'nin Doğu Karadeniz Bölümü'nde yer alan ilin Karadeniz'e kıyısı bulunur. Karadeniz sahili ile Doğu Karadeniz Dağları arasında yer almakta olup yüzölçümü açısından az bir alan kaplar. Batısında Giresun'a bağlı Eynesil ilçesi, güneyinde Gümüşhane'ye bağlı Torul ilçesi ve Bayburt, doğusunda da Rize'ye bağlı İkizdere ve Kalkandere ilçeleri bulunur.\n" +
                            "\n" +
                            "7 Eylül 2010 tarih ve 27695 sayılı resmi gazetede yayımlanan karar ile birlikte 7 belde ve 29 köy tüzel kişilikleri kaldırılarak belediye sınırlarına dahil edilmiştir.[2] Bu son düzenleme ile birlikte belediye nüfusu 402.166'ya çıkmıştır.[3]\n" +
                            "\n" +
                            "Trabzon, günümüzde Karadeniz Bölgesi'nin Samsun'dan sonra ikinci büyük kentidir. Trabzon, 12 Kasım 2012 tarihinde kabul edilen büyükşehir yasa tasarısı ile büyükşehir belediyesi olmuş ve merkez ilçe kaldırılarak Ortahisar ilçesi kurulmuştur. Trabzon iki il ile birlikte de \"şehzadeler şehri\" olarak anılır. Evliya Çelebi Trabzon için şöyle demiş: \"Bu şehre küçük İstanbul denilse yeridir. İrem bağları gibi süslü bir şehirdir burası.\"\n" +
                            "\n" +
                            "Activision imzalı dünyaca ünlü savaş oyunu serisi Call of Duty'nin Soğuk Savaş dönemini anlatan Call of Duty: Black ops Cold War oyununun bazı sahneleri Trabzon'da geçmektedir.[4][5]   "
                    62 -> bilgiler.text = "Tunceli \n\nTunceli, Türkiye'nin Doğu Anadolu Bölgesi'nin Yukarı Fırat Bölümünde yer alan bir il.\n" +
                            "\n" +
                            "Kuzeyde ve batıda Munzur Dağları ile Karasu Nehri, doğuda Bingöl Dağları ve Peri Suyu, güneyde Keban Baraj Gölü ile çevrilidir. Anadolu'nun pek çok yerinde olduğu gibi bu bölgede de çağlar boyunca pek çok uygarlık yaşamıştır. Orta Çağdan kalma ve bugün hâlâ iyi durumda bulunan Pertek Kalesi ve Munzur Vadisi Millî Parkı görülmeye değer güzellikleridir.\n" +
                            "\n" +
                            "Tunceli'nin yerleşimleri: Tunceli (merkez), Çemişgezek, Hozat, Mazgirt, Nazımiye, Ovacık, Pertek ve Pülümür'dür. Şubat 2021 TÜİK verilerine göre 8 ilçe, 9 belediye, bu belediyelerde 43 mahalle, ayrıca 364 köy bulunmaktadır.[3]  "
                    63 -> bilgiler.text = "Şanlıurfa \n\nŞanlıurfa, halk arasındaki kısa adıyla Urfa veya eski çağlarda bilinen adıyla Edessa, Türkiye'nin bir ili ve en kalabalık sekizinci şehridir.[3] 2020 yılı verilerine göre nüfusu 2.115.256’dir.[2] Şehrin doğuda Mardin, batıda Gaziantep, kuzeyde Adıyaman, kuzeydoğuda Diyarbakır illeri ve güneyde Suriye ile sınırı vardır. Şanlıurfa'nın 13 ilçesi vardır. Ortalama yükseltisi 518 metre olan Şanlıurfa, 19.451 km2'lik yüzölçümü ile Türkiye'nin en büyük yedinci ilidir.\n" +
                            "\n" +
                            "Yazları son derece sıcak ve kurak bir iklime sahip olan şehir, kışı serin ve nemli geçirir. 2 milyonu aşkın nüfusuyla Güneydoğu Anadolu Bölgesi'nin en kalabalık şehri olan Şanlıurfa, aynı zamanda yaklaşık 20,4 ortanca yaş ile Türkiye'nin en dinamik nüfusa sahip ilidir.[4]\n" +
                            "\n" +
                            "Şehrin yaklaşık 12 km kuzeydoğusunda, MÖ 10.000 yılına ait olduğu düşünülen ve dünyanın bilinen en eski tapınağı olan Göbeklitepe bulunmaktadır. Göbeklitepe'nin keşfi ile birlikte bu bölgenin, tarım devriminin gerçekleştiği ilk insan yerleşimleri ağının bir parçası olduğu ve köklü bir tarihi geçmişinin bulunduğu ispatlanmış oldu.[5]\n" +
                            "\n" +
                            "Halk hikâyelerinde ve dini inançlarda İbrahim Peygamber ve Kral Nemrud hikâyelerine konu olmuş olan, Peygamberler şehri ve kutsal şehir gibi tanımlamalarla anılmış olan şehrin Nemrud tarafından kurulduğuna inanılmıştır. MÖ 1. binyıldan başlayarak Asurlular, Medler, Ahamenişler (Persler), Makedonyalılar, Büyük İskender'in varislerinden biri olan Selevkoslar, Osroene Krallığı ve ardından Roma ile Bizans İmparatorluklarının hakimiyeti altında kalan bu şehir, Hristiyanlık tarihi açısından önemli bir yere sahip olup, Süryani kültürünün merkezi konumundaydı. Urfa, 7. yüzyılda Müslüman Araplar tarafından fethedildikten sonra bu özelliğini yavaş yavaş kaybetse de, ciddi bir Süryani ve Ermeni nüfus, 20. yüzyılın başlarına kadar şehirde varlığını korumuştur. 1516'da Osmanlı padişahı Yavuz Sultan Selim'in Memlûk Devleti'ni Mercidâbık Muharebesi'nde yenmesiyle Osmanlı hakimiyeti altına giren şehir, 1919 yılında önce İngilizler ve ardından Fransızlar tarafından işgal edilene kadar kesintisiz 400 sene Osmanlı idaresinde kaldı. Şehir, 11 Nisan 1920'de işgalden kurtarıldı ve 20 Ekim 1921'de TBMM ve Fransız Hükûmeti arasında imzalanan Ankara Antlaşması ile Türkiye'ye bırakıldı.\n" +
                            "\n" +
                            "Cumhuriyetin ilanından sonra, 1924 yılında il haline getirildi. Urfa ilinin adı, 22 Haziran 1984 tarih ve 18439 sayılı Resmi Gazete’de yayımlanan 3020 sayılı kanunla Şanlıurfa olarak değiştirilmiştir.[6][7][8] 2016 yılında, Şanlıurfa halkının Türk Kurtuluş Savaşı'nda gösterdiği kahramanlıktan dolayı TBMM tarafından şehre İstiklal Madalyası verilmiştir.[9]\n" +
                            "\n" +
                            "Türkiye İstatistik Kurumu’nun (TÜİK) açıkladığı 2011 yılına ilişkin \"Adrese Dayalı Nüfus Kayıt Sistemi Sonuçları\" dikkate alınarak Şanlıurfa, 12 Kasım 2012 tarihli ve 6360 sayılı kanun ile büyükşehir oldu.[10][11]  "
                    64 -> bilgiler.text = "Uşak \n\nUşak, Ege Bölgesi'nde Batı ve Orta Anadolu'yu birbirine bağlayan İç Ege Bölümü'nde Gördes - Uşak Platosu üzerinde bulunan il. 2021 yılı verilerine göre nüfusu 373.183'tür.[3]\n" +
                            "\n" +
                            "Uşak karayoluyla; İzmir'e 211 km, Ankara'ya 368 km ve İstanbul'a 491 km uzaklıktadır. Merkez ilçenin nüfusu 206.234 (TÜİK-2016) olarak tespit edilmiştir. Şubat 2021 TÜİK verilerine göre il nüfusu 369.433'tür. 6 İlçe, 11 belediye, bu belediyelerde 72 mahalle, ayrıca 245 köy bulunmaktadır.[4]  "
                    65 -> bilgiler.text = "Van   \n\nVan (Ermenice: Վան, Kürtçe: Wan,[3] Osmanlıca: فان Fân), Türkiye'nin bir ili ve en kalabalık on dokuzuncu şehri. Doğu Anadolu Bölgesi, Yukarı Murat-Van Bölümü'nde yer alır. Van ili nüfus bakımından bu bölgenin en büyük ilidir. 2021 sonu itibarıyla nüfusu 1.141.015 kişidir.[1] Kuzeyden Ağrı, batıdan Bitlis, güneybatıdan Siirt, güneyden Hakkâri illeriyle, doğudan da İran'la sınırlıdır. Anadolu'nun en büyük kapalı havzası olan Van Gölü kıyısında toprakları verimli, akarsuları bol, iklim koşulları oldukça elverişli bir yerleşim merkezidir. Dünya'nın hâlâ yaşanılan en eski kentlerinden biridir."
                    66 -> bilgiler.text = "Yozgat\n\nYozgat, Türkiye'nin İç Anadolu Bölgesi'nde yer alan bir ildir. Çekerek, Aydıncık ve Kadışehri ilçeleri ise Karadeniz Bölgesi'nde kalır.\n" +
                            "\n" +
                            "Yozgat ili nüfusu 419.095'dir. Bu nüfusun %76,35'i şehirlerde yaşamaktadır (2021 sonu). İlin yüz ölçümü 13.690 km2dir. İlde km2ye 31 kişi düşmektedir (Bu sayı merkezde 53’tür.). İlde yıllık nüfus %0,14 azalmıştır.[5] İlin yüz ölçümü 13.690 km2dir.\n" +
                            "\n" +
                            "Şubat 2021 TÜİK verilerine göre 14 ilçe, 36 belediye, bu belediyelerde 234 mahalle, ayrıca 558 köy bulunmaktadır.[5]\n" +
                            "\n" +
                            "İl merkezinin denizden yüksekliği 1.317 metredir.   "
                    67 -> bilgiler.text = "Zonguldak\n\nZonguldak, Zonguldak ilinin merkez ilçesi ve aynı isme sahip şehri. Karadeniz kıyısında bulunan şehir, özellikle limanıyla Türkiye'nin Karadeniz ülkeleriyle arasındaki deniz ticaretinde önemli bir yere sahiptir. Ayrıca Türkiye'nin en zengin taşkömürü madenlerini barındırır.     "
                    68 -> bilgiler.text = "Aksaray  \n\nAksaray, Türkiye'nin İç Anadolu Bölgesi’nde, kısmen Konya Havzası'nda ve kısmen Kapadokya'da yer alan, merkezi Aksaray kenti olan ildir. Daha öncesinde il iken 1933'te ilçe yapılmış ve 15 Haziran 1989 tarih ve 3578 sayılı yasa ile Niğde'den ayrılarak yeniden il olmuştur. Niğde'nin kuzeybatısında, Konya'nın doğusunda, Ankara'nın güneydoğusunda yer almaktadır. 433.055 nüfusa (2022)[3] ve 7.659 km² yüz ölçümüne sahiptir.\n" +
                            "\n" +
                            "2022 yılında TÜİK verilerine göre merkez ilçeyle beraber 8 İlçe, 22 belediye, bu belediyelerde 157 mahalle ve ayrıca 175 köyü vardır.[3] "
                    69 -> bilgiler.text = "Bayburt\n\nBayburt, Doğu Karadeniz'de bulunan ve Çoruh Nehri'ne yaslanan Türkiye'nin bir şehri ve Bayburt ilinin merkezidir.   "
                    70 -> bilgiler.text = "Karaman  \n\nKaraman, Türkiye'nin bir ilidir. İç Anadolu Bölgesi'nde yer alan ilin merkezi Karaman şehridir. Nüfusu: 254.919'dur. (2020 sonu). İlin yüzölçümü 8.678  km2'dir. İlde  km2'ye 29 kişi düşmektedir.[2]\n" +
                            "\n" +
                            "1989 yılında Orta Anadolu'nun gelişmesi maksadıyla alınan kararla Konya ilinden ayrılarak il olmuştur.[3] Karaman'ın merkez, Ayrancı, Kazımkarabekir ilçelerinde Akdeniz iklimine benzer karasal iklim; Ermenek, Başyayla, Sarıveliler ilçelerinde Akdeniz iklimi görülür. Bu nedenle ilde yetişen bitki türleri çeşitlilik göstermektedir. Batı ve kuzeyinde Konya, güneyinde Mersin, güneybatısında Antalya illeri ile çevrilidir.\n" +
                            "\n" +
                            "Karaman, Anadolu'da Türkçenin Karamanoğlu Mehmet Bey tarafından resmî dil ilan edildiği yerdir.[4] "
                    71 -> bilgiler.text = "Kırıkkale \n\nKırıkkale, Türkiye Cumhuriyeti'nin İç Anadolu Bölgesinde yer alan ilidir.\n" +
                            "\n" +
                            "Şehrin adını nereden aldığına dair kesin bir bilgi yoktur. Kırıkköyü ile kentin merkezinde bulunan Kaletepe'nin kısaltılarak birleştirilmesinden ortaya çıktığı söylenir. Bu ismin halk tarafından yakıştırıldığı kanaati yaygın olmakla beraber bölgenin ismi Osmanlı arşiv belgelerinde \"Kırıkkal\" şeklinde geçmektedir. Kırıkkale, 1989 senesinden önce başkent Ankara'ya bağlı bir ilçe iken 21 Haziran 1989 târih ve 3578 sayılı yasa gereğince dönemin başbakanı Turgut Özal tarafından yapılan törenle il olmuştur. İlk vâlisi Fikret Güven, 17 Ağustos 1989 târihinde yapılan törenle il vâliliği görevine başlamıştır.[6]\n" +
                            "\n" +
                            "04 Şubat 2021 TÜİK verilerine göre 9 İlçe, 11 belediye, bu belediyelerde 88 mahalle, ayrıca 185 köy bulunmaktadır.[7]  "
                    72 -> bilgiler.text = "Batman \n\nBatman, Türkiye Cumhuriyeti'nin Güneydoğu Anadolu Bölgesinde yer alan bir ildir.\n" +
                            "\n" +
                            "İl Nüfusu: 620.278'dur. Bu nüfusun %84,27'i şehirlerde yaşamaktadır İlde km²'ye 139 kişi düşmektedir. (Bu sayı merkez ilçede 722'dır. (2020).[3] İlin yüzölçümü 4.477 km²'dir.[4] İl merkezinin denizden yüksekliği: 570 m.'dir.\n" +
                            "\n" +
                            "2020 yılında TÜİK verilerine göre merkez ilçeyle beraber 6 İlçe, 11 belediye, bu belediyelerde 136 mahalle ve ayrıca 283 köyü vardır.\n" +
                            "\n" +
                            "1990 yılına kadar Siirt iline bağlı olan Batman, 16 Mayıs 1990 tarih ve 3647 sayılı kanunla Beşiri, Kozluk ve Sason ilçeleri Siirt'ten, Hasankeyf ve Gercüş ilçeleri Mardin'den alınıp Merkez'e bağlanarak Türkiye'nin 72. ili olmuştur.  "
                    73 -> bilgiler.text = "Şırnak\n\nŞırnak, Doğu Anadolu Bölgesi'nde Şırnak ilinin ve merkez ilçesinin yönetim merkezi olan şehirdir.   "
                    74 -> bilgiler.text = "Bartın \n\nBartın, Türkiye'nin Karadeniz Bölgesi'nde Batı Karadeniz Bölümündeki bir ildir. 1991 yılında Zonguldak ilinden ayrılarak Türkiye'nin 74. ili olmuştur. Doğusunda Kastamonu, güneyinde Karabük, batısında Zonguldak illeri, kuzeyinde Karadeniz bulunur. Orman bakımından zengin olan ilin büyük bir kısmı Küre Dağları Millî Parkı sınırları içerisinde yer almaktadır. Bartın Çayı Türkiye'de üzerinde taşımacılık yapılan tek akarsudur.  "
                    75 -> bilgiler.text = "Ardahan \n\nArdahan, Türkiye'nin kuzeydoğu köşesinde Doğu Anadolu Bölgesi'nde ve kısmen Doğu Karadeniz'de bulunan, Gürcistan sınırında kurulmuş olan bir ildir. İdari merkezi Ardahan kentidir. Batısında Artvin, güneybatısında Erzurum, güneyinde Kars illeri ve doğuda Gürcistan ile sınır teşkil etmektedir. Türkiye Cumhuriyeti'nin Kafkaslar'a açılan kapısıdır.\n" +
                            "\n" +
                            "1924 yılında il olmuştur. 1926 yılında Kars iline bağlı bir ilçe olmuştur. 1992 yılında Kars ilinden ayrılarak tekrar il olmuştur.\n" +
                            "\n" +
                            "Ardahan, ilin coğrafi yapısı ve tarihi geçmişinden kaynaklanan kendine özgü doğal ve tarihi değerlere sahiptir. Ardahan, Doğu Anadolu Bölgesi'ne has doğal yapısı ve ikliminin yanında Doğu Karadeniz Bölümü'nün topoğrafyasına, iklimine ve bitki örtüsüne geçiş yerleri ile farklı güzellikleri bir arada barındırmaktadır. Yüksek ovaları, akarsuları, ormanları, zengin çiçek çeşitliliğine sahip yaylaları ve iki gölü ile Ardahan keşfedilmeyi bek\u00ADleyen bir doğa cennetidir.\n" +
                            "\n" +
                            "Gürcistan - Ardahan arasında Türkgözü ve Çıldır Aktaş Sınır Kapısı olmak üzere toplam iki adet sınır kapısı bulunmaktadır.  "
                    76 -> bilgiler.text = "Iğdır \n\nIğdır, Türkiye'nin Doğu Anadolu Bölgesi'nde Erzurum - Kars Bölümü'nde ve Türkiye'nin en doğusunda yer alan bir ildir.\n" +
                            "\n" +
                            "Önemli bir kültür kavşağında bulunan il Ermenistan, Nahçıvan Özerk Cumhuriyeti ve İran ile sınır komşusudur ve Türkiye'nin üç ülkeyle sınırı olan tek ilidir.\n" +
                            "\n" +
                            "Türkiye'nin en yüksek dağı olan Ağrı Dağı'nın yüz ölçümünün üçte biri, il merkezine bağlı Suveren köyü'nün sınırları içindedir.  "
                    77 -> bilgiler.text = "Yalova \n\nYalova, Yalova ilinin merkezi olan ilçedir. 6 Haziran 1995 tarihinde kurulan Yalova ilinin merkez ilçesi olmuştur.\n" +
                            "\n" +
                            "\n" +
                            "Termal yakınlarındaki Sudüşen Şelalesinde turistler Yalova\n" +
                            "Armutlu Yarımadası'nın kuzey kıyısı ile Samanlı Dağları'nın kuzey eteklerine kurulmuş olan Yalova, Türkiye'nin kuzeybatısında, Marmara bölgesinin güneydoğu kesiminde yer almaktadır. İlin kuzeyinde ve batısında Marmara Denizi, doğusunda Kocaeli, güneyinde Bursa (Orhangazi-Gemlik ve İznik ilçeleri) ve Gemlik körfezi yer almaktadır. Yalova ilinin kuzeyinden güneybatısına kadar olan sınırları Marmara Denizi ile çevrilmiştir.\n" +
                            "\n" +
                            "Kıyılar, girintili çıkıntılı bir özellik göstermez. Yalova'nın 39-40º kuzey enlemi, 29-61º doğu boylamları arasında denizden yüksekliği 2 metre, en yüksek noktası 926 metredir. 839 kilometrekarelik alanı ile ülke yüzölçümünün %0,11'lik bölümünü kapsamaktadır.\n" +
                            "\n" +
                            "Yalova, yüzölçümü itibarıyla Türkiye'nin en küçük ilidir ve 105 km ile denize en uzun kıyısı olan turistik illerinden de birisidir.[2]\n" +
                            "\n" +
                            "Yalova, verimli ve bereketli ovalara sahiptir. Çınarcık, Gökçedere, Kirazlı, Kılıçköy ve Taşköprü ile deniz arasında birbirinden alçak tepeciklerle ayrılan büyüklü küçüklü ovalar oluşmuştur. Bu ovalar, akarsular boyunca uzanmakta olup çevrelerinde meyvecilik ve sebzecilik yapılmaktadır.\n" +
                            "\n" +
                            "Yalova'nın toplam yüzölçümünün (84.700 ha) %82'si, tarım arazisi (22.173 ha), orman alanı (46.809 ha) ve çayır-mera arazisinden (7.944 ha) oluşmaktadır.\n" +
                            "\n" +
                            "İlin bitki örtüsünü makiler ve ormanlar oluşturmaktadır. Samanlı Dağları'nın kuzey ve güneyinde vadi içlerinde bulunan makiler, bu kütlenin etekleri boyunca kesintili şeritler ve parçalar halinde bulunurlar.\n" +
                            "\n" +
                            "Yalova'nın güneyindeki dik yamaçlar gür bir orman örtüsü ile tamamen kaplıdır. Ormanlık alanlarda genellikle kayın, meşe, gürgen, kızılcık, kestane ve ıhlamur ağaçları görülür. Yalova'daki ormanlardan çevrenin odun ve kereste ihtiyacı karşılanmaktadır.\n" +
                            "\n" +
                            "Yalova il sınırları ekolojik çeşitliliği kadar etnik ve kültürel çeşitliliğiyle de zenginlik göstermektedir. Anadolu'nun her yanından aldığı göçlerle hem inançsal hem de dilsel çeşitliliği artmıştır. İl genelinde Türkçeden başka Pomakça, Avarca, Çerkesçe, Lazca, Gürcüce, Dargice, Kürtçe, Boşnakça, Tatarca/Karaçayca konuşan etnik grupların yerleşimleri bulunmaktadır. Ayrıca İzel, Şebnem Ferah, İbrahim Kutluay, Mehmet Okur, Hasan Zeybek gibi ünlü isimler Yalova doğumludur. "
                    78 -> bilgiler.text = "Karabük \n\nKarabük, Türkiye'nin kuzeyinde Karadeniz Bölgesi'nde il. 2020 yılı sonu TUİK verilerine göre nüfusu 243.614'dür.[3]\n" +
                            "\n" +
                            "Karabük, 1937 yılına kadar, Safranbolu'ya bağlı Öğlebeli Köyü'nün 13 hanelik bir mahallesiydi. 1935 yılında açılan Ankara-Zonguldak demiryolunun üzerinde yer alıyordu. Demiryolu ile taşıma imkânının varlığı ve kömür yataklarının yakınlığı nedeniyle, burada bir demir çelik fabrikası kurulması kararlaştırıldı. 3 Nisan 1937'de Atatürk'ün talimatıyla, İsmet İnönü, hâlâ Karabük'ün en önemli geçim kaynağı olan Karabük Demir Çelik Fabrikası'nın temellerini attı.\n" +
                            "\n" +
                            "Karabük, 6 Haziran 1995'te, Çankırı'nın Ovacık ve Eskipazar ilçeleri ile Zonguldak'ın Yenice, Safranbolu ve Eflani ilçelerinin birleştirilmesiyle Türkiye'nin 78. ili oldu.   "
                    79 -> bilgiler.text = "Kilis  \n\nKilis, Türkiye'nin Güneydoğu Anadolu Bölgesi'nde bulunan Kilis ilinin merkez ilçesidir. "
                    80 -> bilgiler.text = "Osmaniye\n\nOsmaniye, Türkiye Cumhuriyeti’nin 80. ilidir. 1933'e kadar il olan Osmaniye'nin eski adı Cebelibereket'tir. O tarihte Adana iline bağlanmış, 24 Ekim 1996 tarihinde yapılan yasal düzenlemeyle tekrar il olmuştur. Akdeniz Bölgesi’nde, Çukurova’nın en doğusunda yer alır. 3.767 kilometrekarelik yüzölçümüne sahip Osmaniye topraklarının %42’si ormanlık alan,% 39’si ekili dikili tarım alanı, %17’si tarıma elverişsiz arazi ve %2’si diğer arazilerden oluşmaktadır. 2020 sonu itibarıyla nüfusu 553.012'tir.[3] İdari olarak 7 ilçeye ayrılmıştır.   "
                    81 -> bilgiler.text = "Düzce \n\nDüzce, Türkiye Cumhuriyeti'nin Karadeniz Bölgesi'nin Batı Karadeniz Bölümü'nde yer alan ildir. Düzce ili nüfusu: 405.131 (2022) Bu nüfusun %68,8i şehirlerde yaşamaktadır (2020 sonu). İlin yüzölçümü 2.492 km2'dir.\n" +
                            "\n" +
                            "04 Şubat 2021 TÜİK verilerine göre  merkez ilçeyle beraber 8 İlçe, 10 belediye, bu belediyelerde 115 mahalle, ayrıca 278 köy bulunmaktadır.[3]  "

                    else -> {
                        bilgiler.text = "Böyle bir plaka bulunamadı başına '0' koymadan deneyiniz"
                    }
                }

            } else {
                bilgiler.text = "Lütfen geçerli bir 'PLAKA' kodu giriniz"
            }
            plakatext.text.clear()
        }
    }
}